// <auto-generated />
using System;
using Hms.Emr.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hms.Emr.Data.Migrations
{
    [DbContext(typeof(EmrDbContext))]
    [Migration("20260802195429_Hardening0039")]
    partial class Hardening0039
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("emr")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hms.Emr.Data.Favourite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("doctor_id");

                    b.Property<string>("Dose")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("dose");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("drug_name");

                    b.Property<string>("Duration")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("duration");

                    b.Property<string>("Frequency")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("frequency");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_favourite");

                    b.HasIndex("DoctorId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_favourite_doctor_id_product_id");

                    b.ToTable("favourite", "emr");
                });

            modelBuilder.Entity("Hms.Emr.Data.GlucoseReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AdmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("admission_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<short>("GlucoseTenths")
                        .HasColumnType("smallint")
                        .HasColumnName("glucose_tenths");

                    b.Property<string>("InsulinRoute")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("insulin_route");

                    b.Property<short?>("InsulinUnits")
                        .HasColumnType("smallint")
                        .HasColumnName("insulin_units");

                    b.Property<long>("RecordedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("recorded_by");

                    b.Property<string>("Timing")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("timing");

                    b.HasKey("Id")
                        .HasName("pk_glucose_reading");

                    b.HasIndex("AdmissionId", "At")
                        .HasDatabaseName("ix_glucose_reading_admission_id_at");

                    b.ToTable("glucose_reading", "emr", t =>
                        {
                            t.HasCheckConstraint("ck_glucose_insulin", "insulin_units IS NULL OR insulin_units BETWEEN 0 AND 200");

                            t.HasCheckConstraint("ck_glucose_value", "glucose_tenths BETWEEN 5 AND 500");
                        });
                });

            modelBuilder.Entity("Hms.Emr.Data.MarDose", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("AdministeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("administered_at");

                    b.Property<long?>("AdministeredBy")
                        .HasColumnType("bigint")
                        .HasColumnName("administered_by");

                    b.Property<long>("AdmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("admission_id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Dose")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("dose");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("drug_name");

                    b.Property<string>("Route")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("route");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("state");

                    b.Property<string>("StateReason")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("state_reason");

                    b.HasKey("Id")
                        .HasName("pk_mar_dose");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_mar_dose_state");

                    b.HasIndex("AdmissionId", "ScheduledAt")
                        .HasDatabaseName("ix_mar_dose_admission_id_scheduled_at");

                    b.ToTable("mar_dose", "emr", t =>
                        {
                            t.HasCheckConstraint("ck_mar_dose_given", "state <> 'given' OR (administered_at IS NOT NULL AND administered_by IS NOT NULL)");

                            t.HasCheckConstraint("ck_mar_dose_reason", "state NOT IN ('missed','refused') OR state_reason IS NOT NULL");

                            t.HasCheckConstraint("ck_mar_dose_state", "state IN ('scheduled','given','missed','refused')");
                        });
                });

            modelBuilder.Entity("Hms.Emr.Data.Note", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AdmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("admission_id");

                    b.Property<string>("Advice")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("advice");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Complaint")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("complaint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("diagnosis");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("doctor_id");

                    b.Property<long?>("EncounterId")
                        .HasColumnType("bigint")
                        .HasColumnName("encounter_id");

                    b.Property<DateTimeOffset?>("FinalisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalised_at");

                    b.Property<long?>("FinalisedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("finalised_by");

                    b.Property<DateOnly?>("FollowUpOn")
                        .HasColumnType("date")
                        .HasColumnName("follow_up_on");

                    b.Property<string>("OnExamination")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("on_examination");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("state");

                    b.Property<long?>("SupersedesId")
                        .HasColumnType("bigint")
                        .HasColumnName("supersedes_id");

                    b.HasKey("Id")
                        .HasName("pk_note");

                    b.HasIndex("AdmissionId")
                        .HasDatabaseName("ix_note_admission_id");

                    b.HasIndex("EncounterId")
                        .HasDatabaseName("ix_note_encounter_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_note_patient_id");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_note_state");

                    b.HasIndex("SupersedesId")
                        .IsUnique()
                        .HasDatabaseName("ix_note_supersedes_id")
                        .HasFilter("supersedes_id IS NOT NULL");

                    b.ToTable("note", "emr", t =>
                        {
                            t.HasCheckConstraint("ck_note_finalised", "state NOT IN ('final','superseded') OR (finalised_at IS NOT NULL AND finalised_by IS NOT NULL)");

                            t.HasCheckConstraint("ck_note_parent", "num_nonnulls(encounter_id, admission_id) = 1");

                            t.HasCheckConstraint("ck_note_state", "state IN ('draft','final','superseded')");
                        });
                });

            modelBuilder.Entity("Hms.Emr.Data.NoteDrug", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Dose")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("dose");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("drug_name");

                    b.Property<string>("Duration")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("duration");

                    b.Property<string>("Frequency")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("frequency");

                    b.Property<string>("Instruction")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("instruction");

                    b.Property<long>("NoteId")
                        .HasColumnType("bigint")
                        .HasColumnName("note_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_note_drug");

                    b.HasIndex("NoteId")
                        .HasDatabaseName("ix_note_drug_note_id");

                    b.ToTable("note_drug", "emr");
                });

            modelBuilder.Entity("Hms.Emr.Data.NoteTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Advice")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("advice");

                    b.Property<string>("Complaint")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("complaint");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("diagnosis");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("doctor_id");

                    b.Property<string>("Drugs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("drugs");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OnExamination")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("on_examination");

                    b.HasKey("Id")
                        .HasName("pk_template");

                    b.HasIndex("DoctorId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_template_doctor_id_name");

                    b.ToTable("template", "emr");
                });

            modelBuilder.Entity("Hms.Emr.Data.ReceiveNote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AdmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("admission_id");

                    b.Property<string>("Belongings")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("belongings");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Condition")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("condition");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<long>("ReceivedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("received_by");

                    b.Property<string>("ReceivedFrom")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("received_from");

                    b.HasKey("Id")
                        .HasName("pk_receive_note");

                    b.HasIndex("AdmissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_receive_note_admission_id");

                    b.ToTable("receive_note", "emr");
                });

            modelBuilder.Entity("Hms.Emr.Data.Vitals", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AdmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("admission_id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<short?>("Diastolic")
                        .HasColumnType("smallint")
                        .HasColumnName("diastolic");

                    b.Property<long?>("EncounterId")
                        .HasColumnType("bigint")
                        .HasColumnName("encounter_id");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<short?>("Pulse")
                        .HasColumnType("smallint")
                        .HasColumnName("pulse");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<long>("RecordedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("recorded_by");

                    b.Property<short?>("SpO2")
                        .HasColumnType("smallint")
                        .HasColumnName("sp_o2");

                    b.Property<short?>("Systolic")
                        .HasColumnType("smallint")
                        .HasColumnName("systolic");

                    b.Property<short?>("TemperatureTenthsC")
                        .HasColumnType("smallint")
                        .HasColumnName("temperature_tenths_c");

                    b.Property<short?>("WeightTenthsKg")
                        .HasColumnType("smallint")
                        .HasColumnName("weight_tenths_kg");

                    b.HasKey("Id")
                        .HasName("pk_vitals");

                    b.HasIndex("EncounterId")
                        .HasDatabaseName("ix_vitals_encounter_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_vitals_patient_id");

                    b.ToTable("vitals", "emr", t =>
                        {
                            t.HasCheckConstraint("ck_vitals_diastolic", "diastolic IS NULL OR diastolic BETWEEN 20 AND 200");

                            t.HasCheckConstraint("ck_vitals_parent", "num_nonnulls(encounter_id, admission_id) = 1");

                            t.HasCheckConstraint("ck_vitals_pulse", "pulse IS NULL OR pulse BETWEEN 20 AND 300");

                            t.HasCheckConstraint("ck_vitals_spo2", "sp_o2 IS NULL OR sp_o2 BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_vitals_systolic", "systolic IS NULL OR systolic BETWEEN 40 AND 300");

                            t.HasCheckConstraint("ck_vitals_temperature", "temperature_tenths_c IS NULL OR temperature_tenths_c BETWEEN 250 AND 460");

                            t.HasCheckConstraint("ck_vitals_weight", "weight_tenths_kg IS NULL OR weight_tenths_kg BETWEEN 1 AND 4000");
                        });
                });

            modelBuilder.Entity("Hms.Emr.Data.Note", b =>
                {
                    b.HasOne("Hms.Emr.Data.Note", null)
                        .WithMany()
                        .HasForeignKey("SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_note_note_supersedes_id");
                });

            modelBuilder.Entity("Hms.Emr.Data.NoteDrug", b =>
                {
                    b.HasOne("Hms.Emr.Data.Note", null)
                        .WithMany()
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_note_drug_note_note_id");
                });
#pragma warning restore 612, 618
        }
    }
}
