// <auto-generated />
using System;
using Hms.Billing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hms.Billing.Data.Migrations
{
    [DbContext(typeof(BillDbContext))]
    [Migration("20260726130403_DashboardReadModel")]
    partial class DashboardReadModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bill")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hms.Billing.Data.ChargeLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("CatalogId")
                        .HasColumnType("bigint")
                        .HasColumnName("catalog_id");

                    b.Property<string>("CatalogKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("catalog_kind");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("DescriptionSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_snapshot");

                    b.Property<long?>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("doctor_id");

                    b.Property<long?>("EncounterId")
                        .HasColumnType("bigint")
                        .HasColumnName("encounter_id");

                    b.Property<long?>("FolioId")
                        .HasColumnType("bigint")
                        .HasColumnName("folio_id");

                    b.Property<long?>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<long?>("RateVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("rate_version_id");

                    b.Property<long?>("ReferrerId")
                        .HasColumnType("bigint")
                        .HasColumnName("referrer_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_module");

                    b.Property<long?>("TestOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("test_order_id");

                    b.Property<long>("UnitPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_charge_line");

                    b.ToTable("charge_line", "bill", t =>
                        {
                            t.HasCheckConstraint("ck_charge_parent", "num_nonnulls(encounter_id, folio_id) = 1");
                        });
                });

            modelBuilder.Entity("Hms.Billing.Data.Counter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_counter");

                    b.ToTable("counter", "bill");
                });

            modelBuilder.Entity("Hms.Billing.Data.CounterSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateOnly>("BusinessDay")
                        .HasColumnType("date")
                        .HasColumnName("business_day");

                    b.Property<bool>("CarryClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("carry_closed");

                    b.Property<long?>("CloseApprovedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("close_approved_by");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<long?>("CountedCash")
                        .HasColumnType("bigint")
                        .HasColumnName("counted_cash");

                    b.Property<long>("CounterId")
                        .HasColumnType("bigint")
                        .HasColumnName("counter_id");

                    b.Property<long?>("ExpectedCash")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_cash");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<long>("OpeningFloat")
                        .HasColumnType("bigint")
                        .HasColumnName("opening_float");

                    b.Property<long>("OperatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("operator_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<long?>("Variance")
                        .HasColumnType("bigint")
                        .HasColumnName("variance");

                    b.HasKey("Id")
                        .HasName("pk_counter_session");

                    b.ToTable("counter_session", "bill");
                });

            modelBuilder.Entity("Hms.Billing.Data.DayCloseSummary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateOnly>("BusinessDay")
                        .HasColumnType("date")
                        .HasColumnName("business_day");

                    b.Property<long>("CounterSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("counter_session_id");

                    b.Property<string>("DeptSplit")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("dept_split");

                    b.Property<long>("Discount")
                        .HasColumnType("bigint")
                        .HasColumnName("discount");

                    b.Property<long>("DueCollected")
                        .HasColumnType("bigint")
                        .HasColumnName("due_collected");

                    b.Property<long>("DueCreated")
                        .HasColumnType("bigint")
                        .HasColumnName("due_created");

                    b.Property<long>("Gross")
                        .HasColumnType("bigint")
                        .HasColumnName("gross");

                    b.Property<long>("Net")
                        .HasColumnType("bigint")
                        .HasColumnName("net");

                    b.Property<long>("Refunds")
                        .HasColumnType("bigint")
                        .HasColumnName("refunds");

                    b.Property<long?>("Supersedes")
                        .HasColumnType("bigint")
                        .HasColumnName("supersedes");

                    b.Property<string>("TenderTotals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tender_totals");

                    b.Property<long>("Variance")
                        .HasColumnType("bigint")
                        .HasColumnName("variance");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_day_close_summary");

                    b.HasIndex("CounterSessionId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_day_close_summary_counter_session_id_version");

                    b.ToTable("day_close_summary", "bill");
                });

            modelBuilder.Entity("Hms.Billing.Data.Due", b =>
                {
                    b.Property<long>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("InvoiceId"));

                    b.Property<long>("Balance")
                        .HasColumnType("bigint")
                        .HasColumnName("balance");

                    b.Property<string>("LastFollowup")
                        .HasColumnType("text")
                        .HasColumnName("last_followup");

                    b.HasKey("InvoiceId")
                        .HasName("pk_due");

                    b.ToTable("due", "bill");
                });

            modelBuilder.Entity("Hms.Billing.Data.Encounter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("CounterId")
                        .HasColumnType("bigint")
                        .HasColumnName("counter_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<long?>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("doctor_id");

                    b.Property<DateOnly>("OnDate")
                        .HasColumnType("date")
                        .HasColumnName("on_date");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_encounter");

                    b.ToTable("encounter", "bill");
                });

            modelBuilder.Entity("Hms.Billing.Data.Invoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("CounterSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("counter_session_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<long>("Discount")
                        .HasColumnType("bigint")
                        .HasColumnName("discount");

                    b.Property<long?>("DiscountApprovalId")
                        .HasColumnType("bigint")
                        .HasColumnName("discount_approval_id");

                    b.Property<long>("EncounterId")
                        .HasColumnType("bigint")
                        .HasColumnName("encounter_id");

                    b.Property<string>("FiscalYear")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fiscal_year");

                    b.Property<long>("Gross")
                        .HasColumnType("bigint")
                        .HasColumnName("gross");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_no");

                    b.Property<long>("Net")
                        .HasColumnType("bigint")
                        .HasColumnName("net");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<short>("RoundingAdj")
                        .HasColumnType("smallint")
                        .HasColumnName("rounding_adj");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<long>("Tax")
                        .HasColumnType("bigint")
                        .HasColumnName("tax");

                    b.Property<string>("TaxCode")
                        .HasColumnType("text")
                        .HasColumnName("tax_code");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_invoice");

                    b.HasIndex("InvoiceNo")
                        .IsUnique()
                        .HasDatabaseName("ix_invoice_invoice_no");

                    b.ToTable("invoice", "bill", t =>
                        {
                            t.HasCheckConstraint("ck_invoice_identity", "net = gross - discount + tax + rounding_adj");
                        });
                });

            modelBuilder.Entity("Hms.Billing.Data.InvoiceLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<long>("ChargeLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("charge_line_id");

                    b.Property<string>("DescriptionSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_snapshot");

                    b.Property<long?>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("doctor_id");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<long?>("RateVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("rate_version_id");

                    b.Property<long?>("ReferrerId")
                        .HasColumnType("bigint")
                        .HasColumnName("referrer_id");

                    b.Property<long>("UnitPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_invoice_line");

                    b.ToTable("invoice_line", "bill");
                });

            modelBuilder.Entity("Hms.Billing.Data.Receipt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<long?>("ApprovalId")
                        .HasColumnType("bigint")
                        .HasColumnName("approval_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("CounterSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("counter_session_id");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<long>("OperatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("operator_id");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("receipt_no");

                    b.Property<long?>("RefundOfReceipt")
                        .HasColumnType("bigint")
                        .HasColumnName("refund_of_receipt");

                    b.Property<string>("Tender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tender");

                    b.Property<string>("TenderRef")
                        .HasColumnType("text")
                        .HasColumnName("tender_ref");

                    b.HasKey("Id")
                        .HasName("pk_receipt");

                    b.HasIndex("CounterSessionId")
                        .HasDatabaseName("ix_receipt_counter_session_id");

                    b.HasIndex("ReceiptNo")
                        .IsUnique()
                        .HasDatabaseName("ix_receipt_receipt_no");

                    b.ToTable("receipt", "bill");
                });
#pragma warning restore 612, 618
        }
    }
}
