// <auto-generated />
using System;
using Hms.Billing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hms.Billing.Data.Migrations
{
    [DbContext(typeof(BillDbContext))]
    partial class BillDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bill")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hms.Billing.Data.ChargeLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("CatalogId")
                        .HasColumnType("bigint")
                        .HasColumnName("catalog_id");

                    b.Property<string>("CatalogKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("catalog_kind");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("DescriptionSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description_snapshot");

                    b.Property<long?>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("doctor_id");

                    b.Property<long?>("EncounterId")
                        .HasColumnType("bigint")
                        .HasColumnName("encounter_id");

                    b.Property<long?>("FolioId")
                        .HasColumnType("bigint")
                        .HasColumnName("folio_id");

                    b.Property<long?>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<long?>("RateVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("rate_version_id");

                    b.Property<long?>("ReferrerId")
                        .HasColumnType("bigint")
                        .HasColumnName("referrer_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source_module");

                    b.Property<long?>("TestOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("test_order_id");

                    b.Property<long>("UnitPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_charge_line");

                    b.HasIndex("EncounterId")
                        .HasDatabaseName("ix_charge_line_unbilled_encounter")
                        .HasFilter("invoice_id IS NULL");

                    b.HasIndex("FolioId")
                        .HasDatabaseName("ix_charge_line_unbilled_folio")
                        .HasFilter("invoice_id IS NULL");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_charge_line_invoice_id");

                    b.ToTable("charge_line", "bill", t =>
                        {
                            t.HasCheckConstraint("ck_charge_line_money", "unit_price >= 0 AND amount = qty::bigint * unit_price");

                            t.HasCheckConstraint("ck_charge_line_qty", "qty <> 0 AND qty BETWEEN -9999 AND 9999");

                            t.HasCheckConstraint("ck_charge_parent", "num_nonnulls(encounter_id, folio_id) = 1");
                        });
                });

            modelBuilder.Entity("Hms.Billing.Data.Counter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_counter");

                    b.ToTable("counter", "bill");
                });

            modelBuilder.Entity("Hms.Billing.Data.CounterSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateOnly>("BusinessDay")
                        .HasColumnType("date")
                        .HasColumnName("business_day");

                    b.Property<bool>("CarryClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("carry_closed");

                    b.Property<long?>("CloseApprovedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("close_approved_by");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<long?>("CountedCash")
                        .HasColumnType("bigint")
                        .HasColumnName("counted_cash");

                    b.Property<long>("CounterId")
                        .HasColumnType("bigint")
                        .HasColumnName("counter_id");

                    b.Property<long?>("ExpectedCash")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_cash");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<long>("OpeningFloat")
                        .HasColumnType("bigint")
                        .HasColumnName("opening_float");

                    b.Property<long>("OperatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("operator_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("state");

                    b.Property<long?>("Variance")
                        .HasColumnType("bigint")
                        .HasColumnName("variance");

                    b.HasKey("Id")
                        .HasName("pk_counter_session");

                    b.HasIndex("CounterId")
                        .HasDatabaseName("ix_counter_session_counter_id");

                    b.ToTable("counter_session", "bill", t =>
                        {
                            t.HasCheckConstraint("ck_session_closed_complete", "state <> 'closed' OR (closed_at IS NOT NULL AND counted_cash IS NOT NULL AND expected_cash IS NOT NULL AND variance IS NOT NULL)");

                            t.HasCheckConstraint("ck_session_opening_float", "opening_float >= 0");

                            t.HasCheckConstraint("ck_session_state", "state IN ('opened','active','close_pending','closed','reopened')");
                        });
                });

            modelBuilder.Entity("Hms.Billing.Data.DayCloseSummary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AdvancesTaken")
                        .HasColumnType("bigint")
                        .HasColumnName("advances_taken");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateOnly>("BusinessDay")
                        .HasColumnType("date")
                        .HasColumnName("business_day");

                    b.Property<long>("CounterSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("counter_session_id");

                    b.Property<string>("DeptSplit")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("dept_split");

                    b.Property<long>("Discount")
                        .HasColumnType("bigint")
                        .HasColumnName("discount");

                    b.Property<long>("DueCollected")
                        .HasColumnType("bigint")
                        .HasColumnName("due_collected");

                    b.Property<long>("DueCreated")
                        .HasColumnType("bigint")
                        .HasColumnName("due_created");

                    b.Property<long>("Gross")
                        .HasColumnType("bigint")
                        .HasColumnName("gross");

                    b.Property<long>("Net")
                        .HasColumnType("bigint")
                        .HasColumnName("net");

                    b.Property<long>("Refunds")
                        .HasColumnType("bigint")
                        .HasColumnName("refunds");

                    b.Property<long?>("Supersedes")
                        .HasColumnType("bigint")
                        .HasColumnName("supersedes");

                    b.Property<string>("TenderTotals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tender_totals");

                    b.Property<long>("Variance")
                        .HasColumnType("bigint")
                        .HasColumnName("variance");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_day_close_summary");

                    b.HasIndex("CounterSessionId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_day_close_summary_counter_session_id_version");

                    b.ToTable("day_close_summary", "bill");
                });

            modelBuilder.Entity("Hms.Billing.Data.Due", b =>
                {
                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint")
                        .HasColumnName("balance");

                    b.Property<string>("LastFollowup")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_followup");

                    b.HasKey("InvoiceId")
                        .HasName("pk_due");

                    b.ToTable("due", "bill", t =>
                        {
                            t.HasCheckConstraint("ck_due_balance", "balance >= 0");
                        });
                });

            modelBuilder.Entity("Hms.Billing.Data.Encounter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("CounterId")
                        .HasColumnType("bigint")
                        .HasColumnName("counter_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<long?>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("doctor_id");

                    b.Property<DateOnly>("OnDate")
                        .HasColumnType("date")
                        .HasColumnName("on_date");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("state");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_encounter");

                    b.HasIndex("CounterId")
                        .HasDatabaseName("ix_encounter_counter_id");

                    b.HasIndex("OnDate", "Type")
                        .HasDatabaseName("ix_encounter_on_date_type");

                    b.HasIndex("PatientId", "OnDate")
                        .HasDatabaseName("ix_encounter_patient_id_on_date");

                    b.ToTable("encounter", "bill", t =>
                        {
                            t.HasCheckConstraint("ck_encounter_state", "state IN ('open','closed')");
                        });
                });

            modelBuilder.Entity("Hms.Billing.Data.Invoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("CounterSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("counter_session_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<long>("Discount")
                        .HasColumnType("bigint")
                        .HasColumnName("discount");

                    b.Property<long?>("DiscountApprovalId")
                        .HasColumnType("bigint")
                        .HasColumnName("discount_approval_id");

                    b.Property<long?>("EncounterId")
                        .HasColumnType("bigint")
                        .HasColumnName("encounter_id");

                    b.Property<string>("FiscalYear")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("fiscal_year");

                    b.Property<long?>("FolioId")
                        .HasColumnType("bigint")
                        .HasColumnName("folio_id");

                    b.Property<long>("Gross")
                        .HasColumnType("bigint")
                        .HasColumnName("gross");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("invoice_no");

                    b.Property<long>("Net")
                        .HasColumnType("bigint")
                        .HasColumnName("net");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<short>("RoundingAdj")
                        .HasColumnType("smallint")
                        .HasColumnName("rounding_adj");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("state");

                    b.Property<Guid?>("SubmissionToken")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_token");

                    b.Property<long>("Tax")
                        .HasColumnType("bigint")
                        .HasColumnName("tax");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tax_code");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_invoice");

                    b.HasIndex("CounterSessionId")
                        .HasDatabaseName("ix_invoice_counter_session_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_invoice_created_at");

                    b.HasIndex("InvoiceNo")
                        .IsUnique()
                        .HasDatabaseName("ix_invoice_invoice_no");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_invoice_patient_id");

                    b.HasIndex("SubmissionToken")
                        .IsUnique()
                        .HasDatabaseName("ix_invoice_submission_token")
                        .HasFilter("submission_token IS NOT NULL");

                    b.ToTable("invoice", "bill", t =>
                        {
                            t.HasCheckConstraint("ck_invoice_bounds", "gross >= 0 AND tax >= 0 AND discount BETWEEN 0 AND gross");

                            t.HasCheckConstraint("ck_invoice_identity", "net = gross - discount + tax + rounding_adj");

                            t.HasCheckConstraint("ck_invoice_parent", "num_nonnulls(encounter_id, folio_id) = 1");

                            t.HasCheckConstraint("ck_invoice_state", "state IN ('draft','billed','partially_paid','paid','cancelled','refunded')");
                        });
                });

            modelBuilder.Entity("Hms.Billing.Data.InvoiceLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<long>("ChargeLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("charge_line_id");

                    b.Property<string>("DescriptionSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description_snapshot");

                    b.Property<long?>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("doctor_id");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<long?>("RateVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("rate_version_id");

                    b.Property<long?>("ReferrerId")
                        .HasColumnType("bigint")
                        .HasColumnName("referrer_id");

                    b.Property<long>("UnitPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_invoice_line");

                    b.HasIndex("ChargeLineId")
                        .HasDatabaseName("ix_invoice_line_charge_line_id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_invoice_line_invoice_id");

                    b.ToTable("invoice_line", "bill", t =>
                        {
                            t.HasCheckConstraint("ck_invoice_line_money", "unit_price >= 0 AND amount = qty::bigint * unit_price");

                            t.HasCheckConstraint("ck_invoice_line_qty", "qty <> 0 AND qty BETWEEN -9999 AND 9999");
                        });
                });

            modelBuilder.Entity("Hms.Billing.Data.Receipt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<long?>("ApprovalId")
                        .HasColumnType("bigint")
                        .HasColumnName("approval_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("CounterSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("counter_session_id");

                    b.Property<long?>("FolioId")
                        .HasColumnType("bigint")
                        .HasColumnName("folio_id");

                    b.Property<long?>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<long>("OperatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("operator_id");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("receipt_no");

                    b.Property<long?>("RefundOfReceipt")
                        .HasColumnType("bigint")
                        .HasColumnName("refund_of_receipt");

                    b.Property<string>("Tender")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tender");

                    b.Property<string>("TenderRef")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tender_ref");

                    b.HasKey("Id")
                        .HasName("pk_receipt");

                    b.HasIndex("CounterSessionId")
                        .HasDatabaseName("ix_receipt_counter_session_id");

                    b.HasIndex("FolioId")
                        .HasDatabaseName("ix_receipt_folio_id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_receipt_invoice_id");

                    b.HasIndex("ReceiptNo")
                        .IsUnique()
                        .HasDatabaseName("ix_receipt_receipt_no");

                    b.ToTable("receipt", "bill", t =>
                        {
                            t.HasCheckConstraint("ck_receipt_parent", "num_nonnulls(invoice_id, folio_id) = 1");

                            t.HasCheckConstraint("ck_receipt_tender", "tender IN ('cash','card','bkash','nagad','corporate')");
                        });
                });

            modelBuilder.Entity("Hms.Billing.Data.ChargeLine", b =>
                {
                    b.HasOne("Hms.Billing.Data.Encounter", null)
                        .WithMany()
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_charge_line_encounter_encounter_id");

                    b.HasOne("Hms.Billing.Data.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_charge_line_invoices_invoice_id");
                });

            modelBuilder.Entity("Hms.Billing.Data.CounterSession", b =>
                {
                    b.HasOne("Hms.Billing.Data.Counter", null)
                        .WithMany()
                        .HasForeignKey("CounterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_counter_session_counter_counter_id");
                });

            modelBuilder.Entity("Hms.Billing.Data.DayCloseSummary", b =>
                {
                    b.HasOne("Hms.Billing.Data.CounterSession", null)
                        .WithMany()
                        .HasForeignKey("CounterSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_day_close_summary_counter_session_counter_session_id");
                });

            modelBuilder.Entity("Hms.Billing.Data.Due", b =>
                {
                    b.HasOne("Hms.Billing.Data.Invoice", null)
                        .WithOne()
                        .HasForeignKey("Hms.Billing.Data.Due", "InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_due_invoice_invoice_id");
                });

            modelBuilder.Entity("Hms.Billing.Data.Encounter", b =>
                {
                    b.HasOne("Hms.Billing.Data.Counter", null)
                        .WithMany()
                        .HasForeignKey("CounterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_encounter_counters_counter_id");
                });

            modelBuilder.Entity("Hms.Billing.Data.Invoice", b =>
                {
                    b.HasOne("Hms.Billing.Data.CounterSession", null)
                        .WithMany()
                        .HasForeignKey("CounterSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_counter_session_counter_session_id");
                });

            modelBuilder.Entity("Hms.Billing.Data.InvoiceLine", b =>
                {
                    b.HasOne("Hms.Billing.Data.ChargeLine", null)
                        .WithMany()
                        .HasForeignKey("ChargeLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_line_charge_line_charge_line_id");

                    b.HasOne("Hms.Billing.Data.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_line_invoice_invoice_id");
                });

            modelBuilder.Entity("Hms.Billing.Data.Receipt", b =>
                {
                    b.HasOne("Hms.Billing.Data.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_receipt_invoice_invoice_id");
                });
#pragma warning restore 612, 618
        }
    }
}
