// <auto-generated />
using System;
using Hms.Appointments.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hms.Appointments.Data.Migrations
{
    [DbContext(typeof(ApptDbContext))]
    partial class ApptDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("appt")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hms.Appointments.Data.Appointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("doctor_id");

                    b.Property<DateOnly>("OnDate")
                        .HasColumnType("date")
                        .HasColumnName("on_date");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<int>("SerialNo")
                        .HasColumnType("integer")
                        .HasColumnName("serial_no");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_appointment");

                    b.HasIndex("DoctorId", "OnDate", "SerialNo")
                        .IsUnique()
                        .HasDatabaseName("ix_appointment_doctor_id_on_date_serial_no");

                    b.ToTable("appointment", "appt");
                });

            modelBuilder.Entity("Hms.Appointments.Data.DoctorSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("doctor_id");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doctor_name");

                    b.Property<int>("MaxSerials")
                        .HasColumnType("integer")
                        .HasColumnName("max_serials");

                    b.Property<string>("Room")
                        .HasColumnType("text")
                        .HasColumnName("room");

                    b.Property<TimeOnly>("SlotFrom")
                        .HasColumnType("time without time zone")
                        .HasColumnName("slot_from");

                    b.Property<TimeOnly>("SlotTo")
                        .HasColumnType("time without time zone")
                        .HasColumnName("slot_to");

                    b.Property<int>("Weekday")
                        .HasColumnType("integer")
                        .HasColumnName("weekday");

                    b.HasKey("Id")
                        .HasName("pk_doctor_schedule");

                    b.ToTable("doctor_schedule", "appt");
                });
#pragma warning restore 612, 618
        }
    }
}
