// <auto-generated />
using System;
using Hms.Pharmacy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hms.Pharmacy.Data.Migrations
{
    [DbContext(typeof(PharmDbContext))]
    partial class PharmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pharm")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hms.Pharmacy.Data.Batch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("batch_no");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("Cost")
                        .HasColumnType("bigint")
                        .HasColumnName("cost");

                    b.Property<DateOnly>("Expiry")
                        .HasColumnType("date")
                        .HasColumnName("expiry");

                    b.Property<long>("Mrp")
                        .HasColumnType("bigint")
                        .HasColumnName("mrp");

                    b.Property<long>("OutletId")
                        .HasColumnType("bigint")
                        .HasColumnName("outlet_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<long?>("PurchaseOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("purchase_order_id");

                    b.Property<int>("QtyOnHand")
                        .HasColumnType("integer")
                        .HasColumnName("qty_on_hand");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<long>("ReceivedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("received_by");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("StateReason")
                        .HasColumnType("text")
                        .HasColumnName("state_reason");

                    b.HasKey("Id")
                        .HasName("pk_batch");

                    b.HasIndex("OutletId", "ProductId", "State", "Expiry")
                        .HasDatabaseName("ix_batch_outlet_id_product_id_state_expiry");

                    b.ToTable("batch", "pharm", t =>
                        {
                            t.HasCheckConstraint("ck_batch_qty", "qty_on_hand >= 0");
                        });
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_company");

                    b.ToTable("company", "pharm");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.IssueAllocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("ChargeLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("charge_line_id");

                    b.Property<long>("IndentId")
                        .HasColumnType("bigint")
                        .HasColumnName("indent_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<int>("ReturnedQty")
                        .HasColumnType("integer")
                        .HasColumnName("returned_qty");

                    b.Property<long>("UnitCost")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_cost");

                    b.Property<long>("UnitMrp")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_mrp");

                    b.HasKey("Id")
                        .HasName("pk_issue_allocation");

                    b.HasIndex("IndentId")
                        .HasDatabaseName("ix_issue_allocation_indent_id");

                    b.ToTable("issue_allocation", "pharm");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.Outlet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_outlet");

                    b.ToTable("outlet", "pharm");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.PharmProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("form");

                    b.Property<string>("Generic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("generic");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("integer")
                        .HasColumnName("reorder_level");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strength");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.HasIndex("Brand", "Generic")
                        .HasDatabaseName("ix_product_brand_generic");

                    b.ToTable("product", "pharm");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.PurchaseOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ApprovalId")
                        .HasColumnType("bigint")
                        .HasColumnName("approval_id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<long>("OutletId")
                        .HasColumnType("bigint")
                        .HasColumnName("outlet_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id")
                        .HasName("pk_purchase_order");

                    b.ToTable("purchase_order", "pharm");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.PurchaseOrderLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExpectedCost")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_cost");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<long>("PurchaseOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("purchase_order_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<int>("ReceivedQty")
                        .HasColumnType("integer")
                        .HasColumnName("received_qty");

                    b.HasKey("Id")
                        .HasName("pk_purchase_order_line");

                    b.ToTable("purchase_order_line", "pharm");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.SaleAllocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("ChargeLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("charge_line_id");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<int>("RefundedQty")
                        .HasColumnType("integer")
                        .HasColumnName("refunded_qty");

                    b.Property<long>("UnitCost")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_cost");

                    b.Property<long>("UnitMrp")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_mrp");

                    b.HasKey("Id")
                        .HasName("pk_sale_allocation");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_sale_allocation_invoice_id");

                    b.ToTable("sale_allocation", "pharm");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.StockAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ApprovalId")
                        .HasColumnType("bigint")
                        .HasColumnName("approval_id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("OutletId")
                        .HasColumnType("bigint")
                        .HasColumnName("outlet_id");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<long>("StartedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("started_by");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_stock_audit");

                    b.ToTable("stock_audit", "pharm");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.StockAuditLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.Property<int>("CountedQty")
                        .HasColumnType("integer")
                        .HasColumnName("counted_qty");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<long>("StockAuditId")
                        .HasColumnType("bigint")
                        .HasColumnName("stock_audit_id");

                    b.Property<int>("SystemQty")
                        .HasColumnType("integer")
                        .HasColumnName("system_qty");

                    b.HasKey("Id")
                        .HasName("pk_stock_audit_line");

                    b.ToTable("stock_audit_line", "pharm");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.StockMove", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActorId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<long>("OutletId")
                        .HasColumnType("bigint")
                        .HasColumnName("outlet_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<long?>("RefId")
                        .HasColumnType("bigint")
                        .HasColumnName("ref_id");

                    b.Property<string>("RefTable")
                        .HasColumnType("text")
                        .HasColumnName("ref_table");

                    b.HasKey("Id")
                        .HasName("pk_stock_move");

                    b.HasIndex("BatchId", "At")
                        .HasDatabaseName("ix_stock_move_batch_id_at");

                    b.HasIndex("ProductId", "At")
                        .HasDatabaseName("ix_stock_move_product_id_at");

                    b.ToTable("stock_move", "pharm");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.Supplier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_supplier");

                    b.ToTable("supplier", "pharm");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.SupplierLedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActorId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<long?>("RefId")
                        .HasColumnType("bigint")
                        .HasColumnName("ref_id");

                    b.Property<string>("RefTable")
                        .HasColumnType("text")
                        .HasColumnName("ref_table");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id")
                        .HasName("pk_supplier_ledger");

                    b.HasIndex("SupplierId", "At")
                        .HasDatabaseName("ix_supplier_ledger_supplier_id_at");

                    b.ToTable("supplier_ledger", "pharm");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.Transfer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<long>("FromOutletId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_outlet_id");

                    b.Property<DateTimeOffset?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<long?>("ReceivedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("received_by");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<long>("ToOutletId")
                        .HasColumnType("bigint")
                        .HasColumnName("to_outlet_id");

                    b.HasKey("Id")
                        .HasName("pk_transfer");

                    b.ToTable("transfer", "pharm");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.TransferBatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("batch_no");

                    b.Property<long>("Cost")
                        .HasColumnType("bigint")
                        .HasColumnName("cost");

                    b.Property<DateOnly>("Expiry")
                        .HasColumnType("date")
                        .HasColumnName("expiry");

                    b.Property<long>("Mrp")
                        .HasColumnType("bigint")
                        .HasColumnName("mrp");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<long>("SourceBatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_batch_id");

                    b.Property<long>("TransferId")
                        .HasColumnType("bigint")
                        .HasColumnName("transfer_id");

                    b.HasKey("Id")
                        .HasName("pk_transfer_batch");

                    b.ToTable("transfer_batch", "pharm");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.TransferLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("RequestedQty")
                        .HasColumnType("integer")
                        .HasColumnName("requested_qty");

                    b.Property<int>("SentQty")
                        .HasColumnType("integer")
                        .HasColumnName("sent_qty");

                    b.Property<long>("TransferId")
                        .HasColumnType("bigint")
                        .HasColumnName("transfer_id");

                    b.HasKey("Id")
                        .HasName("pk_transfer_line");

                    b.ToTable("transfer_line", "pharm");
                });
#pragma warning restore 612, 618
        }
    }
}
