// <auto-generated />
using System;
using Hms.Pharmacy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hms.Pharmacy.Data.Migrations
{
    [DbContext(typeof(PharmDbContext))]
    partial class PharmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pharm")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hms.Pharmacy.Data.Batch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("batch_no");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("Cost")
                        .HasColumnType("bigint")
                        .HasColumnName("cost");

                    b.Property<DateOnly>("Expiry")
                        .HasColumnType("date")
                        .HasColumnName("expiry");

                    b.Property<long>("Mrp")
                        .HasColumnType("bigint")
                        .HasColumnName("mrp");

                    b.Property<long>("OutletId")
                        .HasColumnType("bigint")
                        .HasColumnName("outlet_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<long?>("PurchaseOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("purchase_order_id");

                    b.Property<int>("QtyOnHand")
                        .HasColumnType("integer")
                        .HasColumnName("qty_on_hand");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<long>("ReceivedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("received_by");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("state");

                    b.Property<string>("StateReason")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("state_reason");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_batch");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("ix_batch_purchase_order_id");

                    b.HasIndex("ProductId", "State", "Expiry")
                        .HasDatabaseName("ix_batch_product_id_state_expiry");

                    b.HasIndex("OutletId", "ProductId", "State", "Expiry")
                        .HasDatabaseName("ix_batch_outlet_id_product_id_state_expiry");

                    b.ToTable("batch", "pharm", t =>
                        {
                            t.HasCheckConstraint("ck_batch_money", "cost >= 0 AND mrp >= 0");

                            t.HasCheckConstraint("ck_batch_qty", "qty_on_hand >= 0");

                            t.HasCheckConstraint("ck_batch_state", "state IN ('instock','quarantined','returned','disposed')");
                        });
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_company");

                    b.ToTable("company", "pharm");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.IssueAllocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("ChargeLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("charge_line_id");

                    b.Property<long>("IndentId")
                        .HasColumnType("bigint")
                        .HasColumnName("indent_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<int>("ReturnedQty")
                        .HasColumnType("integer")
                        .HasColumnName("returned_qty");

                    b.Property<long>("UnitCost")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_cost");

                    b.Property<long>("UnitMrp")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_mrp");

                    b.HasKey("Id")
                        .HasName("pk_issue_allocation");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_issue_allocation_batch_id");

                    b.HasIndex("IndentId")
                        .HasDatabaseName("ix_issue_allocation_indent_id");

                    b.ToTable("issue_allocation", "pharm", t =>
                        {
                            t.HasCheckConstraint("ck_issue_allocation_qty", "returned_qty BETWEEN 0 AND qty");
                        });
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.Outlet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_outlet");

                    b.ToTable("outlet", "pharm");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.PharmProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("brand");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("form");

                    b.Property<string>("Generic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("generic");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("integer")
                        .HasColumnName("reorder_level");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("strength");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_product_company_id");

                    b.HasIndex("Brand", "Generic")
                        .HasDatabaseName("ix_product_brand_generic");

                    b.ToTable("product", "pharm");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.PurchaseOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ApprovalId")
                        .HasColumnType("bigint")
                        .HasColumnName("approval_id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<long>("OutletId")
                        .HasColumnType("bigint")
                        .HasColumnName("outlet_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("state");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id")
                        .HasName("pk_purchase_order");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_purchase_order_supplier_id");

                    b.ToTable("purchase_order", "pharm", t =>
                        {
                            t.HasCheckConstraint("ck_purchase_order_state", "state IN ('requested','approved','ordered','partially_received','received','closed','cancelled')");
                        });
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.PurchaseOrderLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExpectedCost")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_cost");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<long>("PurchaseOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("purchase_order_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<int>("ReceivedQty")
                        .HasColumnType("integer")
                        .HasColumnName("received_qty");

                    b.HasKey("Id")
                        .HasName("pk_purchase_order_line");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("ix_purchase_order_line_purchase_order_id");

                    b.ToTable("purchase_order_line", "pharm", t =>
                        {
                            t.HasCheckConstraint("ck_po_line_qty", "qty > 0 AND expected_cost >= 0 AND received_qty BETWEEN 0 AND qty");
                        });
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.SaleAllocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("ChargeLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("charge_line_id");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<int>("RefundedQty")
                        .HasColumnType("integer")
                        .HasColumnName("refunded_qty");

                    b.Property<long>("UnitCost")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_cost");

                    b.Property<long>("UnitMrp")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_mrp");

                    b.HasKey("Id")
                        .HasName("pk_sale_allocation");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_sale_allocation_batch_id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_sale_allocation_invoice_id");

                    b.ToTable("sale_allocation", "pharm", t =>
                        {
                            t.HasCheckConstraint("ck_sale_allocation_money", "unit_mrp >= 0 AND unit_cost >= 0");

                            t.HasCheckConstraint("ck_sale_allocation_qty", "qty > 0 AND refunded_qty BETWEEN 0 AND qty");
                        });
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.StockAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ApprovalId")
                        .HasColumnType("bigint")
                        .HasColumnName("approval_id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("OutletId")
                        .HasColumnType("bigint")
                        .HasColumnName("outlet_id");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<long>("StartedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("started_by");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_stock_audit");

                    b.ToTable("stock_audit", "pharm", t =>
                        {
                            t.HasCheckConstraint("ck_stock_audit_state", "state IN ('count_started','variance_listed','approved','posted')");
                        });
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.StockAuditLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.Property<int>("CountedQty")
                        .HasColumnType("integer")
                        .HasColumnName("counted_qty");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<long>("StockAuditId")
                        .HasColumnType("bigint")
                        .HasColumnName("stock_audit_id");

                    b.Property<int>("SystemQty")
                        .HasColumnType("integer")
                        .HasColumnName("system_qty");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_stock_audit_line");

                    b.HasIndex("StockAuditId")
                        .HasDatabaseName("ix_stock_audit_line_stock_audit_id");

                    b.ToTable("stock_audit_line", "pharm", t =>
                        {
                            t.HasCheckConstraint("ck_stock_audit_line_counted", "counted_qty >= 0");
                        });
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.StockMove", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActorId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<long>("OutletId")
                        .HasColumnType("bigint")
                        .HasColumnName("outlet_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<string>("Reason")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("reason");

                    b.Property<long?>("RefId")
                        .HasColumnType("bigint")
                        .HasColumnName("ref_id");

                    b.Property<string>("RefTable")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ref_table");

                    b.HasKey("Id")
                        .HasName("pk_stock_move");

                    b.HasIndex("BatchId", "At")
                        .HasDatabaseName("ix_stock_move_batch_id_at");

                    b.HasIndex("ProductId", "At")
                        .HasDatabaseName("ix_stock_move_product_id_at");

                    b.ToTable("stock_move", "pharm");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.Supplier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_supplier");

                    b.ToTable("supplier", "pharm");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.SupplierLedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActorId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("note");

                    b.Property<long?>("RefId")
                        .HasColumnType("bigint")
                        .HasColumnName("ref_id");

                    b.Property<string>("RefTable")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ref_table");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id")
                        .HasName("pk_supplier_ledger");

                    b.HasIndex("SupplierId", "At")
                        .HasDatabaseName("ix_supplier_ledger_supplier_id_at");

                    b.ToTable("supplier_ledger", "pharm");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.Transfer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<long>("FromOutletId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_outlet_id");

                    b.Property<DateTimeOffset?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<long?>("ReceivedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("received_by");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("state");

                    b.Property<long>("ToOutletId")
                        .HasColumnType("bigint")
                        .HasColumnName("to_outlet_id");

                    b.HasKey("Id")
                        .HasName("pk_transfer");

                    b.ToTable("transfer", "pharm", t =>
                        {
                            t.HasCheckConstraint("ck_transfer_received", "state <> 'received' OR (received_at IS NOT NULL AND received_by IS NOT NULL)");

                            t.HasCheckConstraint("ck_transfer_sent", "state <> 'sent' OR sent_at IS NOT NULL");

                            t.HasCheckConstraint("ck_transfer_state", "state IN ('indent','sent','received','cancelled')");
                        });
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.TransferBatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("batch_no");

                    b.Property<long>("Cost")
                        .HasColumnType("bigint")
                        .HasColumnName("cost");

                    b.Property<DateOnly>("Expiry")
                        .HasColumnType("date")
                        .HasColumnName("expiry");

                    b.Property<long>("Mrp")
                        .HasColumnType("bigint")
                        .HasColumnName("mrp");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<long>("SourceBatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_batch_id");

                    b.Property<long>("TransferId")
                        .HasColumnType("bigint")
                        .HasColumnName("transfer_id");

                    b.HasKey("Id")
                        .HasName("pk_transfer_batch");

                    b.ToTable("transfer_batch", "pharm");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.TransferLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("RequestedQty")
                        .HasColumnType("integer")
                        .HasColumnName("requested_qty");

                    b.Property<int>("SentQty")
                        .HasColumnType("integer")
                        .HasColumnName("sent_qty");

                    b.Property<long>("TransferId")
                        .HasColumnType("bigint")
                        .HasColumnName("transfer_id");

                    b.HasKey("Id")
                        .HasName("pk_transfer_line");

                    b.HasIndex("TransferId")
                        .HasDatabaseName("ix_transfer_line_transfer_id");

                    b.ToTable("transfer_line", "pharm", t =>
                        {
                            t.HasCheckConstraint("ck_transfer_line_qty", "sent_qty BETWEEN 0 AND requested_qty");
                        });
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.Batch", b =>
                {
                    b.HasOne("Hms.Pharmacy.Data.Outlet", null)
                        .WithMany()
                        .HasForeignKey("OutletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_batch_outlet_outlet_id");

                    b.HasOne("Hms.Pharmacy.Data.PharmProduct", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_batch_product_product_id");

                    b.HasOne("Hms.Pharmacy.Data.PurchaseOrder", null)
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_batch_purchase_order_purchase_order_id");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.IssueAllocation", b =>
                {
                    b.HasOne("Hms.Pharmacy.Data.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_issue_allocation_batch_batch_id");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.PharmProduct", b =>
                {
                    b.HasOne("Hms.Pharmacy.Data.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_company_company_id");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.PurchaseOrder", b =>
                {
                    b.HasOne("Hms.Pharmacy.Data.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_supplier_supplier_id");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.PurchaseOrderLine", b =>
                {
                    b.HasOne("Hms.Pharmacy.Data.PurchaseOrder", null)
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_line_purchase_order_purchase_order_id");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.SaleAllocation", b =>
                {
                    b.HasOne("Hms.Pharmacy.Data.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sale_allocation_batch_batch_id");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.StockAuditLine", b =>
                {
                    b.HasOne("Hms.Pharmacy.Data.StockAudit", null)
                        .WithMany()
                        .HasForeignKey("StockAuditId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_audit_line_stock_audit_stock_audit_id");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.StockMove", b =>
                {
                    b.HasOne("Hms.Pharmacy.Data.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_move_batch_batch_id");

                    b.HasOne("Hms.Pharmacy.Data.PharmProduct", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_move_product_product_id");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.SupplierLedgerEntry", b =>
                {
                    b.HasOne("Hms.Pharmacy.Data.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_ledger_supplier_supplier_id");
                });

            modelBuilder.Entity("Hms.Pharmacy.Data.TransferLine", b =>
                {
                    b.HasOne("Hms.Pharmacy.Data.Transfer", null)
                        .WithMany()
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transfer_line_transfer_transfer_id");
                });
#pragma warning restore 612, 618
        }
    }
}
