// <auto-generated />
using System;
using Hms.Ipd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hms.Ipd.Data.Migrations
{
    [DbContext(typeof(IpdDbContext))]
    [Migration("20260727092725_InitIpd")]
    partial class InitIpd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ipd")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hms.Ipd.Data.Admission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdmissionNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("admission_no");

                    b.Property<DateTimeOffset>("AdmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("admitted_at");

                    b.Property<long?>("BlockApprovalId")
                        .HasColumnType("bigint")
                        .HasColumnName("block_approval_id");

                    b.Property<string>("BlockedFrom")
                        .HasColumnType("text")
                        .HasColumnName("blocked_from");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("ClinicalSummary")
                        .HasColumnType("text")
                        .HasColumnName("clinical_summary");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DischargedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discharged_at");

                    b.Property<long?>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("doctor_id");

                    b.Property<long?>("PackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<string>("ProvisionalDx")
                        .HasColumnType("text")
                        .HasColumnName("provisional_dx");

                    b.Property<short>("ServiceChargePct")
                        .HasColumnType("smallint")
                        .HasColumnName("service_charge_pct");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_admission");

                    b.HasIndex("AdmissionNo")
                        .IsUnique()
                        .HasDatabaseName("ix_admission_admission_no");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_admission_patient_id");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_admission_state");

                    b.ToTable("admission", "ipd");
                });

            modelBuilder.Entity("Hms.Ipd.Data.AdmissionPackage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<short>("DefaultServiceChargePct")
                        .HasColumnType("smallint")
                        .HasColumnName("default_service_charge_pct");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("ServiceCatalogId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_catalog_id");

                    b.HasKey("Id")
                        .HasName("pk_admission_package");

                    b.ToTable("admission_package", "ipd");
                });

            modelBuilder.Entity("Hms.Ipd.Data.Bed", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("StateReason")
                        .HasColumnType("text")
                        .HasColumnName("state_reason");

                    b.Property<long>("TariffServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("tariff_service_id");

                    b.Property<long>("WardId")
                        .HasColumnType("bigint")
                        .HasColumnName("ward_id");

                    b.HasKey("Id")
                        .HasName("pk_bed");

                    b.HasIndex("WardId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_bed_ward_id_code");

                    b.ToTable("bed", "ipd");
                });

            modelBuilder.Entity("Hms.Ipd.Data.BedDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AdmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("admission_id");

                    b.Property<long>("BedId")
                        .HasColumnType("bigint")
                        .HasColumnName("bed_id");

                    b.Property<long>("ChargeLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("charge_line_id");

                    b.Property<DateOnly>("OnDate")
                        .HasColumnType("date")
                        .HasColumnName("on_date");

                    b.HasKey("Id")
                        .HasName("pk_bed_day");

                    b.HasIndex("AdmissionId", "OnDate")
                        .IsUnique()
                        .HasDatabaseName("ix_bed_day_admission_id_on_date");

                    b.ToTable("bed_day", "ipd");
                });

            modelBuilder.Entity("Hms.Ipd.Data.BedStay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AdmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("admission_id");

                    b.Property<long>("BedId")
                        .HasColumnType("bigint")
                        .HasColumnName("bed_id");

                    b.Property<DateTimeOffset>("FromAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("from_at");

                    b.Property<DateTimeOffset?>("ToAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("to_at");

                    b.HasKey("Id")
                        .HasName("pk_bed_stay");

                    b.HasIndex("AdmissionId")
                        .HasDatabaseName("ix_bed_stay_admission_id");

                    b.HasIndex("BedId")
                        .HasDatabaseName("ix_bed_stay_bed_id");

                    b.ToTable("bed_stay", "ipd");
                });

            modelBuilder.Entity("Hms.Ipd.Data.Certificate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AdmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("admission_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("CertNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cert_no");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<long>("IssuedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("issued_by");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int>("PrintCount")
                        .HasColumnType("integer")
                        .HasColumnName("print_count");

                    b.HasKey("Id")
                        .HasName("pk_certificate");

                    b.HasIndex("CertNo")
                        .IsUnique()
                        .HasDatabaseName("ix_certificate_cert_no");

                    b.ToTable("certificate", "ipd");
                });

            modelBuilder.Entity("Hms.Ipd.Data.Folio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AdmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("admission_id");

                    b.Property<long>("AdvanceApplied")
                        .HasColumnType("bigint")
                        .HasColumnName("advance_applied");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<long?>("SettlementInvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("settlement_invoice_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_folio");

                    b.HasIndex("AdmissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_folio_admission_id");

                    b.ToTable("folio", "ipd");
                });

            modelBuilder.Entity("Hms.Ipd.Data.Indent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AdmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("admission_id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("FolioId")
                        .HasColumnType("bigint")
                        .HasColumnName("folio_id");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<long?>("IssuedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("issued_by");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<long>("RequestedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("requested_by");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_indent");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_indent_state");

                    b.ToTable("indent", "ipd");
                });

            modelBuilder.Entity("Hms.Ipd.Data.IndentItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IndentId")
                        .HasColumnType("bigint")
                        .HasColumnName("indent_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("QtyIssued")
                        .HasColumnType("integer")
                        .HasColumnName("qty_issued");

                    b.Property<int>("QtyRequested")
                        .HasColumnType("integer")
                        .HasColumnName("qty_requested");

                    b.Property<int>("QtyReturned")
                        .HasColumnType("integer")
                        .HasColumnName("qty_returned");

                    b.HasKey("Id")
                        .HasName("pk_indent_item");

                    b.HasIndex("IndentId")
                        .HasDatabaseName("ix_indent_item_indent_id");

                    b.ToTable("indent_item", "ipd");
                });

            modelBuilder.Entity("Hms.Ipd.Data.Ward", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("class");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_ward");

                    b.ToTable("ward", "ipd");
                });
#pragma warning restore 612, 618
        }
    }
}
