// <auto-generated />
using System;
using Hms.Ipd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hms.Ipd.Data.Migrations
{
    [DbContext(typeof(IpdDbContext))]
    [Migration("20260803082647_ConsultantVisit")]
    partial class ConsultantVisit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ipd")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hms.Ipd.Data.Admission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdmissionNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("admission_no");

                    b.Property<DateTimeOffset>("AdmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("admitted_at");

                    b.Property<long?>("BlockApprovalId")
                        .HasColumnType("bigint")
                        .HasColumnName("block_approval_id");

                    b.Property<string>("BlockedFrom")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("blocked_from");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("ClinicalSummary")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("clinical_summary");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DischargedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discharged_at");

                    b.Property<long?>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("doctor_id");

                    b.Property<long?>("PackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<string>("ProvisionalDx")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("provisional_dx");

                    b.Property<short>("ServiceChargePct")
                        .HasColumnType("smallint")
                        .HasColumnName("service_charge_pct");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("state");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_admission");

                    b.HasIndex("AdmissionNo")
                        .IsUnique()
                        .HasDatabaseName("ix_admission_admission_no");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_admission_patient_id");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_admission_state");

                    b.ToTable("admission", "ipd", t =>
                        {
                            t.HasCheckConstraint("ck_admission_blocked_from", "blocked_from IS NULL OR blocked_from IN ('reserved','admitted','blocked','discharge_initiated','clinically_cleared','financially_settled','discharged','death','absconded')");

                            t.HasCheckConstraint("ck_admission_discharged", "state NOT IN ('discharged','death','absconded') OR discharged_at IS NOT NULL");

                            t.HasCheckConstraint("ck_admission_service_charge_pct", "service_charge_pct BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_admission_state", "state IN ('reserved','admitted','blocked','discharge_initiated','clinically_cleared','financially_settled','discharged','death','absconded')");
                        });
                });

            modelBuilder.Entity("Hms.Ipd.Data.AdmissionPackage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<short>("DefaultServiceChargePct")
                        .HasColumnType("smallint")
                        .HasColumnName("default_service_charge_pct");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("ServiceCatalogId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_catalog_id");

                    b.HasKey("Id")
                        .HasName("pk_admission_package");

                    b.ToTable("admission_package", "ipd", t =>
                        {
                            t.HasCheckConstraint("ck_admission_package_pct", "default_service_charge_pct BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("Hms.Ipd.Data.Bed", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("state");

                    b.Property<string>("StateReason")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("state_reason");

                    b.Property<long>("TariffServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("tariff_service_id");

                    b.Property<long>("WardId")
                        .HasColumnType("bigint")
                        .HasColumnName("ward_id");

                    b.HasKey("Id")
                        .HasName("pk_bed");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_bed_state");

                    b.HasIndex("WardId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_bed_ward_id_code");

                    b.ToTable("bed", "ipd", t =>
                        {
                            t.HasCheckConstraint("ck_bed_state", "state IN ('free','reserved','occupied','cleaning','out_of_service')");
                        });
                });

            modelBuilder.Entity("Hms.Ipd.Data.BedDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AdmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("admission_id");

                    b.Property<long>("BedId")
                        .HasColumnType("bigint")
                        .HasColumnName("bed_id");

                    b.Property<long>("ChargeLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("charge_line_id");

                    b.Property<DateOnly>("OnDate")
                        .HasColumnType("date")
                        .HasColumnName("on_date");

                    b.HasKey("Id")
                        .HasName("pk_bed_day");

                    b.HasIndex("BedId")
                        .HasDatabaseName("ix_bed_day_bed_id");

                    b.HasIndex("AdmissionId", "OnDate")
                        .IsUnique()
                        .HasDatabaseName("ix_bed_day_admission_id_on_date");

                    b.ToTable("bed_day", "ipd");
                });

            modelBuilder.Entity("Hms.Ipd.Data.BedStay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AdmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("admission_id");

                    b.Property<long>("BedId")
                        .HasColumnType("bigint")
                        .HasColumnName("bed_id");

                    b.Property<DateTimeOffset>("FromAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("from_at");

                    b.Property<DateTimeOffset?>("ToAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("to_at");

                    b.HasKey("Id")
                        .HasName("pk_bed_stay");

                    b.HasIndex("AdmissionId")
                        .HasDatabaseName("ix_bed_stay_admission_id");

                    b.HasIndex("BedId")
                        .HasDatabaseName("ix_bed_stay_bed_id");

                    b.HasIndex(new[] { "AdmissionId" }, "ix_bed_stay_open_admission")
                        .HasDatabaseName("ix_bed_stay_admission_id1")
                        .HasFilter("to_at IS NULL");

                    b.ToTable("bed_stay", "ipd");
                });

            modelBuilder.Entity("Hms.Ipd.Data.Certificate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AdmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("admission_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("CertNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("cert_no");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<long>("IssuedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("issued_by");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<int>("PrintCount")
                        .HasColumnType("integer")
                        .HasColumnName("print_count");

                    b.HasKey("Id")
                        .HasName("pk_certificate");

                    b.HasIndex("AdmissionId")
                        .HasDatabaseName("ix_certificate_admission_id");

                    b.HasIndex("CertNo")
                        .IsUnique()
                        .HasDatabaseName("ix_certificate_cert_no");

                    b.ToTable("certificate", "ipd");
                });

            modelBuilder.Entity("Hms.Ipd.Data.ConsultantVisit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AdmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("admission_id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long?>("ChargeLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("charge_line_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("doctor_id");

                    b.Property<long?>("NoteId")
                        .HasColumnType("bigint")
                        .HasColumnName("note_id");

                    b.Property<DateOnly>("OnDate")
                        .HasColumnType("date")
                        .HasColumnName("on_date");

                    b.HasKey("Id")
                        .HasName("pk_consultant_visit");

                    b.HasIndex("DoctorId", "OnDate")
                        .HasDatabaseName("ix_consultant_visit_doctor_id_on_date");

                    b.HasIndex("AdmissionId", "DoctorId", "OnDate")
                        .IsUnique()
                        .HasDatabaseName("ix_consultant_visit_admission_id_doctor_id_on_date");

                    b.ToTable("consultant_visit", "ipd");
                });

            modelBuilder.Entity("Hms.Ipd.Data.DutyAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<long?>("EndedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("ended_by");

                    b.Property<string>("EndedReason")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("ended_reason");

                    b.Property<DateOnly>("OnDate")
                        .HasColumnType("date")
                        .HasColumnName("on_date");

                    b.Property<string>("ShiftLabel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("shift_label");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("staff_name");

                    b.Property<string>("StaffRole")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("staff_role");

                    b.Property<long>("WardId")
                        .HasColumnType("bigint")
                        .HasColumnName("ward_id");

                    b.HasKey("Id")
                        .HasName("pk_duty_assignment");

                    b.HasIndex("OnDate", "WardId")
                        .HasDatabaseName("ix_duty_assignment_on_date_ward_id");

                    b.HasIndex("WardId", "OnDate", "ShiftLabel", "StaffName")
                        .IsUnique()
                        .HasDatabaseName("ix_duty_assignment_ward_id_on_date_shift_label_staff_name")
                        .HasFilter("active");

                    b.ToTable("duty_assignment", "ipd", t =>
                        {
                            t.HasCheckConstraint("ck_duty_ended", "active OR (ended_reason IS NOT NULL AND ended_at IS NOT NULL AND ended_by IS NOT NULL)");

                            t.HasCheckConstraint("ck_duty_role", "staff_role IN ('nurse','ward-boy','aya')");

                            t.HasCheckConstraint("ck_duty_shift", "shift_label IN ('morning','evening','night')");
                        });
                });

            modelBuilder.Entity("Hms.Ipd.Data.Folio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AdmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("admission_id");

                    b.Property<long>("AdvanceApplied")
                        .HasColumnType("bigint")
                        .HasColumnName("advance_applied");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<long?>("SettlementInvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("settlement_invoice_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("state");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_folio");

                    b.HasIndex("AdmissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_folio_admission_id");

                    b.ToTable("folio", "ipd", t =>
                        {
                            t.HasCheckConstraint("ck_folio_advance", "advance_applied >= 0");

                            t.HasCheckConstraint("ck_folio_locked", "state <> 'locked' OR settlement_invoice_id IS NOT NULL");

                            t.HasCheckConstraint("ck_folio_state", "state IN ('open','blocked','settlement_draft','locked')");
                        });
                });

            modelBuilder.Entity("Hms.Ipd.Data.Indent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AdmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("admission_id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("FolioId")
                        .HasColumnType("bigint")
                        .HasColumnName("folio_id");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<long?>("IssuedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("issued_by");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<long>("RequestedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("requested_by");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_indent");

                    b.HasIndex("AdmissionId")
                        .HasDatabaseName("ix_indent_admission_id");

                    b.HasIndex("FolioId")
                        .HasDatabaseName("ix_indent_folio_id");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_indent_state");

                    b.ToTable("indent", "ipd", t =>
                        {
                            t.HasCheckConstraint("ck_indent_issued", "state <> 'issued' OR (issued_by IS NOT NULL AND issued_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_indent_state", "state IN ('requested','issued','cancelled')");
                        });
                });

            modelBuilder.Entity("Hms.Ipd.Data.IndentItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IndentId")
                        .HasColumnType("bigint")
                        .HasColumnName("indent_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("QtyIssued")
                        .HasColumnType("integer")
                        .HasColumnName("qty_issued");

                    b.Property<int>("QtyRequested")
                        .HasColumnType("integer")
                        .HasColumnName("qty_requested");

                    b.Property<int>("QtyReturned")
                        .HasColumnType("integer")
                        .HasColumnName("qty_returned");

                    b.HasKey("Id")
                        .HasName("pk_indent_item");

                    b.HasIndex("IndentId")
                        .HasDatabaseName("ix_indent_item_indent_id");

                    b.ToTable("indent_item", "ipd", t =>
                        {
                            t.HasCheckConstraint("ck_indent_item_qty", "qty_requested > 0 AND qty_issued BETWEEN 0 AND qty_requested AND qty_returned BETWEEN 0 AND qty_issued");
                        });
                });

            modelBuilder.Entity("Hms.Ipd.Data.Ward", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("class");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_ward");

                    b.ToTable("ward", "ipd");
                });

            modelBuilder.Entity("Hms.Ipd.Data.Bed", b =>
                {
                    b.HasOne("Hms.Ipd.Data.Ward", null)
                        .WithMany()
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bed_ward_ward_id");
                });

            modelBuilder.Entity("Hms.Ipd.Data.BedDay", b =>
                {
                    b.HasOne("Hms.Ipd.Data.Admission", null)
                        .WithMany()
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bed_day_admission_admission_id");

                    b.HasOne("Hms.Ipd.Data.Bed", null)
                        .WithMany()
                        .HasForeignKey("BedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bed_day_bed_bed_id");
                });

            modelBuilder.Entity("Hms.Ipd.Data.BedStay", b =>
                {
                    b.HasOne("Hms.Ipd.Data.Admission", null)
                        .WithMany()
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bed_stay_admission_admission_id");

                    b.HasOne("Hms.Ipd.Data.Bed", null)
                        .WithMany()
                        .HasForeignKey("BedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bed_stay_bed_bed_id");
                });

            modelBuilder.Entity("Hms.Ipd.Data.Certificate", b =>
                {
                    b.HasOne("Hms.Ipd.Data.Admission", null)
                        .WithMany()
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_certificate_admission_admission_id");
                });

            modelBuilder.Entity("Hms.Ipd.Data.ConsultantVisit", b =>
                {
                    b.HasOne("Hms.Ipd.Data.Admission", null)
                        .WithMany()
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consultant_visit_admission_admission_id");
                });

            modelBuilder.Entity("Hms.Ipd.Data.DutyAssignment", b =>
                {
                    b.HasOne("Hms.Ipd.Data.Ward", null)
                        .WithMany()
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_duty_assignment_ward_ward_id");
                });

            modelBuilder.Entity("Hms.Ipd.Data.Folio", b =>
                {
                    b.HasOne("Hms.Ipd.Data.Admission", null)
                        .WithMany()
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_folio_admission_admission_id");
                });

            modelBuilder.Entity("Hms.Ipd.Data.Indent", b =>
                {
                    b.HasOne("Hms.Ipd.Data.Admission", null)
                        .WithMany()
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_indent_admission_admission_id");

                    b.HasOne("Hms.Ipd.Data.Folio", null)
                        .WithMany()
                        .HasForeignKey("FolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_indent_folio_folio_id");
                });

            modelBuilder.Entity("Hms.Ipd.Data.IndentItem", b =>
                {
                    b.HasOne("Hms.Ipd.Data.Indent", null)
                        .WithMany()
                        .HasForeignKey("IndentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_indent_item_indent_indent_id");
                });
#pragma warning restore 612, 618
        }
    }
}
