// <auto-generated />
using System;
using Hms.Diagnostics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hms.Diagnostics.Data.Migrations
{
    [DbContext(typeof(DiagDbContext))]
    partial class DiagDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("diag")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hms.Diagnostics.Data.DeliveryLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CollectorNote")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("collector_note");

                    b.Property<DateTimeOffset>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<long>("DeliveredBy")
                        .HasColumnType("bigint")
                        .HasColumnName("delivered_by");

                    b.Property<int>("ReportVersion")
                        .HasColumnType("integer")
                        .HasColumnName("report_version");

                    b.Property<long>("TestOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("test_order_id");

                    b.HasKey("Id")
                        .HasName("pk_delivery_log");

                    b.HasIndex("TestOrderId")
                        .HasDatabaseName("ix_delivery_log_test_order_id");

                    b.ToTable("delivery_log", "diag");
                });

            modelBuilder.Entity("Hms.Diagnostics.Data.OrderTest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChargeLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("charge_line_id");

                    b.Property<bool>("Refunded")
                        .HasColumnType("boolean")
                        .HasColumnName("refunded");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("state");

                    b.Property<long>("TestCatalogId")
                        .HasColumnType("bigint")
                        .HasColumnName("test_catalog_id");

                    b.Property<long>("TestOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("test_order_id");

                    b.HasKey("Id")
                        .HasName("pk_order_test");

                    b.HasIndex("TestOrderId", "TestCatalogId")
                        .HasDatabaseName("ix_order_test_test_order_id_test_catalog_id");

                    b.ToTable("order_test", "diag", t =>
                        {
                            t.HasCheckConstraint("ck_order_test_state", "state IN ('ordered','cancelled')");
                        });
                });

            modelBuilder.Entity("Hms.Diagnostics.Data.TestOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long?>("CancelApprovalId")
                        .HasColumnType("bigint")
                        .HasColumnName("cancel_approval_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<long?>("EncounterId")
                        .HasColumnType("bigint")
                        .HasColumnName("encounter_id");

                    b.Property<long?>("FolioId")
                        .HasColumnType("bigint")
                        .HasColumnName("folio_id");

                    b.Property<long?>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<long?>("OrderingDoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("ordering_doctor_id");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset>("PromisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("promised_at");

                    b.Property<string>("PublicToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("public_token");

                    b.Property<long?>("ReferrerId")
                        .HasColumnType("bigint")
                        .HasColumnName("referrer_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_test_order");

                    b.HasIndex("EncounterId")
                        .HasDatabaseName("ix_test_order_encounter_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_test_order_patient_id");

                    b.HasIndex("PublicToken")
                        .IsUnique()
                        .HasDatabaseName("ix_test_order_public_token");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_test_order_state");

                    b.HasIndex("InvoiceId", "State")
                        .HasDatabaseName("ix_test_order_invoice_id_state");

                    b.ToTable("test_order", "diag", t =>
                        {
                            t.HasCheckConstraint("ck_test_order_parent", "num_nonnulls(encounter_id, folio_id) = 1");

                            t.HasCheckConstraint("ck_test_order_state", "state IN ('ordered','invoiced','in_progress','reported','delivered','cancelled')");
                        });
                });

            modelBuilder.Entity("Hms.Diagnostics.Data.DeliveryLog", b =>
                {
                    b.HasOne("Hms.Diagnostics.Data.TestOrder", null)
                        .WithMany()
                        .HasForeignKey("TestOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_log_test_order_test_order_id");
                });

            modelBuilder.Entity("Hms.Diagnostics.Data.OrderTest", b =>
                {
                    b.HasOne("Hms.Diagnostics.Data.TestOrder", null)
                        .WithMany()
                        .HasForeignKey("TestOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_test_test_order_test_order_id");
                });
#pragma warning restore 612, 618
        }
    }
}
