// <auto-generated />
using System;
using Hms.Radiology.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hms.Radiology.Data.Migrations
{
    [DbContext(typeof(RadiologyDbContext))]
    partial class RadiologyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("radiology")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hms.Radiology.Data.Modality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_modality");

                    b.HasIndex("BranchId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_modality_branch_id_code");

                    b.ToTable("modality", "radiology");
                });

            modelBuilder.Entity("Hms.Radiology.Data.ModalityTest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ModalityId")
                        .HasColumnType("bigint")
                        .HasColumnName("modality_id");

                    b.Property<long>("TestCatalogId")
                        .HasColumnType("bigint")
                        .HasColumnName("test_catalog_id");

                    b.HasKey("Id")
                        .HasName("pk_modality_test");

                    b.HasIndex("ModalityId")
                        .HasDatabaseName("ix_modality_test_modality_id");

                    b.HasIndex("TestCatalogId")
                        .IsUnique()
                        .HasDatabaseName("ix_modality_test_test_catalog_id");

                    b.ToTable("modality_test", "radiology");
                });

            modelBuilder.Entity("Hms.Radiology.Data.Study", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessionNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("accession_no");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FilmCount")
                        .HasColumnType("integer")
                        .HasColumnName("film_count");

                    b.Property<string>("FilmSize")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("film_size");

                    b.Property<long>("ModalityId")
                        .HasColumnType("bigint")
                        .HasColumnName("modality_id");

                    b.Property<long>("OrderTestId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_test_id");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset?>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<long?>("PerformedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("performed_by");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("state");

                    b.Property<string>("TechnicianNote")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("technician_note");

                    b.HasKey("Id")
                        .HasName("pk_study");

                    b.HasIndex("AccessionNo")
                        .IsUnique()
                        .HasDatabaseName("ix_study_accession_no");

                    b.HasIndex("OrderTestId")
                        .IsUnique()
                        .HasDatabaseName("ix_study_order_test_id");

                    b.HasIndex("ModalityId", "State")
                        .HasDatabaseName("ix_study_modality_id_state");

                    b.ToTable("study", "radiology", t =>
                        {
                            t.HasCheckConstraint("ck_study_film_count", "film_count >= 0");

                            t.HasCheckConstraint("ck_study_state", "state IN ('awaiting','done','reported')");
                        });
                });

            modelBuilder.Entity("Hms.Radiology.Data.ModalityTest", b =>
                {
                    b.HasOne("Hms.Radiology.Data.Modality", null)
                        .WithMany()
                        .HasForeignKey("ModalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_modality_test_modality_modality_id");
                });

            modelBuilder.Entity("Hms.Radiology.Data.Study", b =>
                {
                    b.HasOne("Hms.Radiology.Data.Modality", null)
                        .WithMany()
                        .HasForeignKey("ModalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_study_modality_modality_id");
                });
#pragma warning restore 612, 618
        }
    }
}
