// <auto-generated />
using System;
using Hms.Registration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hms.Registration.Data.Migrations
{
    [DbContext(typeof(RegDbContext))]
    partial class RegDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reg")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hms.Registration.Data.Patient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateOnly?>("AgeAsOf")
                        .HasColumnType("date")
                        .HasColumnName("age_as_of");

                    b.Property<bool>("AgeEstimated")
                        .HasColumnType("boolean")
                        .HasColumnName("age_estimated");

                    b.Property<short?>("AgeMonths")
                        .HasColumnType("smallint")
                        .HasColumnName("age_months");

                    b.Property<short?>("AgeYears")
                        .HasColumnType("smallint")
                        .HasColumnName("age_years");

                    b.Property<string>("Area")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("area");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("blood_group");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Guardian")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("guardian");

                    b.Property<long?>("MergedInto")
                        .HasColumnType("bigint")
                        .HasColumnName("merged_into");

                    b.Property<string>("Nid")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("nid");

                    b.Property<string>("PatientType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("patient_type");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PhoneDigits")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("phone_digits")
                        .HasComputedColumnSql("regexp_replace(coalesce(phone, ''), '\\D', '', 'g')", true);

                    b.Property<bool>("Provisional")
                        .HasColumnType("boolean")
                        .HasColumnName("provisional");

                    b.Property<char>("Sex")
                        .HasColumnType("char(1)")
                        .HasColumnName("sex");

                    b.Property<string>("Uhid")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("uhid");

                    b.Property<bool>("UnknownIdentity")
                        .HasColumnType("boolean")
                        .HasColumnName("unknown_identity");

                    b.HasKey("Id")
                        .HasName("pk_patient");

                    b.HasIndex("MergedInto")
                        .HasDatabaseName("ix_patient_merged_into");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_patient_phone");

                    b.HasIndex("PhoneDigits")
                        .HasDatabaseName("ix_patient_phone_digits");

                    b.HasIndex("Uhid")
                        .IsUnique()
                        .HasDatabaseName("ix_patient_uhid");

                    b.ToTable("patient", "reg", t =>
                        {
                            t.HasCheckConstraint("ck_identity", "dob is not null or age_years is not null or age_months is not null or unknown_identity");

                            t.HasCheckConstraint("ck_patient_age", "(age_years IS NULL OR age_years BETWEEN 0 AND 130) AND (age_months IS NULL OR age_months BETWEEN 0 AND 11)");

                            t.HasCheckConstraint("ck_patient_dob", "dob IS NULL OR (dob >= '1900-01-01' AND dob <= current_date)");
                        });
                });

            modelBuilder.Entity("Hms.Registration.Data.PatientMerge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApprovalId")
                        .HasColumnType("bigint")
                        .HasColumnName("approval_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<long>("By")
                        .HasColumnType("bigint")
                        .HasColumnName("by");

                    b.Property<long>("MergedId")
                        .HasColumnType("bigint")
                        .HasColumnName("merged_id");

                    b.Property<string>("Repointed")
                        .HasColumnType("jsonb")
                        .HasColumnName("repointed");

                    b.Property<long>("SurvivorId")
                        .HasColumnType("bigint")
                        .HasColumnName("survivor_id");

                    b.HasKey("Id")
                        .HasName("pk_patient_merge");

                    b.ToTable("patient_merge", "reg");
                });

            modelBuilder.Entity("Hms.Registration.Data.Patient", b =>
                {
                    b.HasOne("Hms.Registration.Data.Patient", null)
                        .WithMany()
                        .HasForeignKey("MergedInto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_patient_patient_merged_into");
                });
#pragma warning restore 612, 618
        }
    }
}
