// <auto-generated />
using System;
using Hms.Lis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hms.Lis.Data.Migrations
{
    [DbContext(typeof(LisDbContext))]
    [Migration("20260726130111_InitLis")]
    partial class InitLis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("lis")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hms.Lis.Data.LabelPrint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("PrintedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("printed_at");

                    b.Property<long>("PrintedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("printed_by");

                    b.Property<bool>("Reprint")
                        .HasColumnType("boolean")
                        .HasColumnName("reprint");

                    b.Property<long>("SampleId")
                        .HasColumnType("bigint")
                        .HasColumnName("sample_id");

                    b.HasKey("Id")
                        .HasName("pk_label_print");

                    b.ToTable("label_print", "lis");
                });

            modelBuilder.Entity("Hms.Lis.Data.Result", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AmendApprovalId")
                        .HasColumnType("bigint")
                        .HasColumnName("amend_approval_id");

                    b.Property<DateTimeOffset>("EnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entered_at");

                    b.Property<long>("EnteredBy")
                        .HasColumnType("bigint")
                        .HasColumnName("entered_by");

                    b.Property<string>("EsignHash")
                        .HasColumnType("text")
                        .HasColumnName("esign_hash");

                    b.Property<string>("Narrative")
                        .HasColumnType("text")
                        .HasColumnName("narrative");

                    b.Property<long>("OrderTestId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_test_id");

                    b.Property<string>("SignatureImageRef")
                        .HasColumnType("text")
                        .HasColumnName("signature_image_ref");

                    b.Property<int?>("SupersedesVersion")
                        .HasColumnType("integer")
                        .HasColumnName("supersedes_version");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("values");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<long?>("VerifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("verified_by");

                    b.Property<string>("VerifierRole")
                        .HasColumnType("text")
                        .HasColumnName("verifier_role");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_result");

                    b.HasIndex("OrderTestId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_result_order_test_id_version");

                    b.ToTable("result", "lis");
                });

            modelBuilder.Entity("Hms.Lis.Data.Sample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset?>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<long?>("CollectedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("collected_by");

                    b.Property<string>("DisposalNote")
                        .HasColumnType("text")
                        .HasColumnName("disposal_note");

                    b.Property<DateTimeOffset?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<long?>("ReceivedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("received_by");

                    b.Property<long?>("RecollectionOf")
                        .HasColumnType("bigint")
                        .HasColumnName("recollection_of");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("text")
                        .HasColumnName("rejected_reason");

                    b.Property<string>("SampleType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sample_type");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_sample");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("ix_sample_barcode");

                    b.ToTable("sample", "lis");
                });

            modelBuilder.Entity("Hms.Lis.Data.SampleTest", b =>
                {
                    b.Property<long>("SampleId")
                        .HasColumnType("bigint")
                        .HasColumnName("sample_id");

                    b.Property<long>("OrderTestId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_test_id");

                    b.HasKey("SampleId", "OrderTestId")
                        .HasName("pk_sample_test");

                    b.ToTable("sample_test", "lis");
                });
#pragma warning restore 612, 618
        }
    }
}
