// <auto-generated />
using System;
using Hms.Lis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hms.Lis.Data.Migrations
{
    [DbContext(typeof(LisDbContext))]
    [Migration("20260802195435_Hardening0039")]
    partial class Hardening0039
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("lis")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hms.Lis.Data.LabelPrint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("PrintedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("printed_at");

                    b.Property<long>("PrintedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("printed_by");

                    b.Property<bool>("Reprint")
                        .HasColumnType("boolean")
                        .HasColumnName("reprint");

                    b.Property<long>("SampleId")
                        .HasColumnType("bigint")
                        .HasColumnName("sample_id");

                    b.HasKey("Id")
                        .HasName("pk_label_print");

                    b.HasIndex("SampleId")
                        .HasDatabaseName("ix_label_print_sample_id");

                    b.ToTable("label_print", "lis");
                });

            modelBuilder.Entity("Hms.Lis.Data.Result", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AmendApprovalId")
                        .HasColumnType("bigint")
                        .HasColumnName("amend_approval_id");

                    b.Property<DateTimeOffset>("EnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entered_at");

                    b.Property<long>("EnteredBy")
                        .HasColumnType("bigint")
                        .HasColumnName("entered_by");

                    b.Property<string>("EsignHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("esign_hash");

                    b.Property<string>("Narrative")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("narrative");

                    b.Property<long>("OrderTestId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_test_id");

                    b.Property<string>("SignatureImageRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("signature_image_ref");

                    b.Property<int?>("SupersedesVersion")
                        .HasColumnType("integer")
                        .HasColumnName("supersedes_version");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("values");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<long?>("VerifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("verified_by");

                    b.Property<string>("VerifierRole")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("verifier_role");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_result");

                    b.HasIndex("OrderTestId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_result_order_test_id_version");

                    b.ToTable("result", "lis", t =>
                        {
                            t.HasCheckConstraint("ck_result_verified", "verified_at IS NULL OR (verified_by IS NOT NULL AND verifier_role IS NOT NULL AND esign_hash IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Hms.Lis.Data.Sample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("barcode");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset?>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<long?>("CollectedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("collected_by");

                    b.Property<string>("DisposalNote")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("disposal_note");

                    b.Property<DateTimeOffset?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<long?>("ReceivedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("received_by");

                    b.Property<long?>("RecollectionOf")
                        .HasColumnType("bigint")
                        .HasColumnName("recollection_of");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("rejected_reason");

                    b.Property<string>("SampleType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("sample_type");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_sample");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("ix_sample_barcode");

                    b.HasIndex("RecollectionOf")
                        .HasDatabaseName("ix_sample_recollection_of");

                    b.ToTable("sample", "lis", t =>
                        {
                            t.HasCheckConstraint("ck_sample_collected", "state = 'pending_collection' OR (collected_at IS NOT NULL AND collected_by IS NOT NULL)");

                            t.HasCheckConstraint("ck_sample_received", "state IN ('pending_collection','collected') OR (received_at IS NOT NULL AND received_by IS NOT NULL)");

                            t.HasCheckConstraint("ck_sample_rejected", "state <> 'rejected' OR rejected_reason IS NOT NULL");

                            t.HasCheckConstraint("ck_sample_state", "state IN ('pending_collection','collected','received','rejected','resulted','verified','report_ready','delivered')");
                        });
                });

            modelBuilder.Entity("Hms.Lis.Data.SampleTest", b =>
                {
                    b.Property<long>("SampleId")
                        .HasColumnType("bigint")
                        .HasColumnName("sample_id");

                    b.Property<long>("OrderTestId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_test_id");

                    b.HasKey("SampleId", "OrderTestId")
                        .HasName("pk_sample_test");

                    b.HasIndex("OrderTestId")
                        .HasDatabaseName("ix_sample_test_order_test_id");

                    b.ToTable("sample_test", "lis");
                });

            modelBuilder.Entity("Hms.Lis.Data.LabelPrint", b =>
                {
                    b.HasOne("Hms.Lis.Data.Sample", null)
                        .WithMany()
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_label_print_sample_sample_id");
                });

            modelBuilder.Entity("Hms.Lis.Data.Sample", b =>
                {
                    b.HasOne("Hms.Lis.Data.Sample", null)
                        .WithMany()
                        .HasForeignKey("RecollectionOf")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sample_sample_recollection_of");
                });

            modelBuilder.Entity("Hms.Lis.Data.SampleTest", b =>
                {
                    b.HasOne("Hms.Lis.Data.Sample", null)
                        .WithMany()
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sample_test_sample_sample_id");
                });
#pragma warning restore 612, 618
        }
    }
}
