// <auto-generated />
using System;
using Hms.Admin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hms.Admin.Data.Migrations
{
    [DbContext(typeof(AdmDbContext))]
    [Migration("20260727041916_AddReferrerAndReportingConsultant")]
    partial class AddReferrerAndReportingConsultant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("adm")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hms.Admin.Data.RateVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ApprovalId")
                        .HasColumnType("bigint")
                        .HasColumnName("approval_id");

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("CatalogId")
                        .HasColumnType("bigint")
                        .HasColumnName("catalog_id");

                    b.Property<string>("CatalogKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("catalog_kind");

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("price");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_rate_version");

                    b.ToTable("rate_version", "adm");
                });

            modelBuilder.Entity("Hms.Admin.Data.Referrer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Area")
                        .HasColumnType("text")
                        .HasColumnName("area");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<short>("CommissionPercent")
                        .HasColumnType("smallint")
                        .HasColumnName("commission_percent");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_referrer");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_referrer_code");

                    b.ToTable("referrer", "adm");
                });

            modelBuilder.Entity("Hms.Admin.Data.ReportingConsultant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("BmdcNo")
                        .HasColumnType("text")
                        .HasColumnName("bmdc_no");

                    b.Property<string>("Degrees")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("degrees");

                    b.PrimitiveCollection<string[]>("Departments")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("departments");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_reporting_consultant");

                    b.ToTable("reporting_consultant", "adm");
                });

            modelBuilder.Entity("Hms.Admin.Data.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Dept")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dept");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Provisional")
                        .HasColumnType("boolean")
                        .HasColumnName("provisional");

                    b.HasKey("Id")
                        .HasName("pk_service");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_service_code");

                    b.ToTable("service", "adm");
                });

            modelBuilder.Entity("Hms.Admin.Data.TestCatalogItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Dept")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dept");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Provisional")
                        .HasColumnType("boolean")
                        .HasColumnName("provisional");

                    b.PrimitiveCollection<string[]>("SampleTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("sample_types");

                    b.Property<int>("TatMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("tat_minutes");

                    b.Property<string>("Template")
                        .HasColumnType("jsonb")
                        .HasColumnName("template");

                    b.HasKey("Id")
                        .HasName("pk_test_catalog");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_test_catalog_code");

                    b.ToTable("test_catalog", "adm");
                });
#pragma warning restore 612, 618
        }
    }
}
