// <auto-generated />
using System;
using Hms.Admin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hms.Admin.Data.Migrations
{
    [DbContext(typeof(AdmDbContext))]
    partial class AdmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("adm")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hms.Admin.Data.RateVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ApprovalId")
                        .HasColumnType("bigint")
                        .HasColumnName("approval_id");

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("CatalogId")
                        .HasColumnType("bigint")
                        .HasColumnName("catalog_id");

                    b.Property<string>("CatalogKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("catalog_kind");

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("price");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("scope");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_rate_version");

                    b.HasIndex("CatalogKind", "CatalogId", "Scope", "BranchId", "ValidFrom")
                        .HasDatabaseName("ix_rate_version_catalog_kind_catalog_id_scope_branch_id_valid_");

                    b.ToTable("rate_version", "adm", t =>
                        {
                            t.HasCheckConstraint("ck_rate_version_effective_order", "valid_to IS NULL OR valid_to >= valid_from");

                            t.HasCheckConstraint("ck_rate_version_price", "price >= 0");

                            t.HasCheckConstraint("ck_rate_version_window", "valid_from BETWEEN '2000-01-01' AND '2100-01-01'");
                        });
                });

            modelBuilder.Entity("Hms.Admin.Data.Referrer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Area")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("area");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<short>("CommissionPercent")
                        .HasColumnType("smallint")
                        .HasColumnName("commission_percent");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_referrer");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_referrer_code");

                    b.ToTable("referrer", "adm", t =>
                        {
                            t.HasCheckConstraint("ck_referrer_commission", "commission_percent BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("Hms.Admin.Data.ReportingConsultant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("BmdcNo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("bmdc_no");

                    b.Property<string>("Degrees")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("degrees");

                    b.PrimitiveCollection<string[]>("Departments")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("departments");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_reporting_consultant");

                    b.ToTable("reporting_consultant", "adm");
                });

            modelBuilder.Entity("Hms.Admin.Data.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<string>("Dept")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("dept");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool>("Provisional")
                        .HasColumnType("boolean")
                        .HasColumnName("provisional");

                    b.HasKey("Id")
                        .HasName("pk_service");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_service_code");

                    b.ToTable("service", "adm");
                });

            modelBuilder.Entity("Hms.Admin.Data.TestCatalogItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<string>("Dept")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("dept");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool>("Provisional")
                        .HasColumnType("boolean")
                        .HasColumnName("provisional");

                    b.PrimitiveCollection<string[]>("SampleTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("sample_types");

                    b.Property<int>("TatMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("tat_minutes");

                    b.Property<string>("Template")
                        .HasColumnType("jsonb")
                        .HasColumnName("template");

                    b.HasKey("Id")
                        .HasName("pk_test_catalog");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_test_catalog_code");

                    b.ToTable("test_catalog", "adm", t =>
                        {
                            t.HasCheckConstraint("ck_test_catalog_tat", "tat_minutes >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
