using Hms.Kernel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;

namespace Hms.Diagnostics.Data;

// diag.* per 03 §7. The TestOrder machine (02 §2.8) is guarded by state-checked UPDATEs.

public static class TestOrderState
{
    public const string Ordered = "ordered";
    public const string Invoiced = "invoiced";
    public const string InProgress = "in_progress";
    public const string Reported = "reported";
    public const string Delivered = "delivered";
    public const string Cancelled = "cancelled";
}

public class TestOrder
{
    public long Id { get; set; }
    public long BranchId { get; set; }
    public long PatientId { get; set; }
    public long? EncounterId { get; set; }
    public long? FolioId { get; set; }                 // indoor parent (M6, spec 0017) — XOR below
    public long? OrderingDoctorId { get; set; }
    public long? ReferrerId { get; set; }              // payout attribution (ADR-0017)
    public string State { get; set; } = TestOrderState.Ordered;
    public DateTimeOffset PromisedAt { get; set; }     // TAT promise (§9A.2)
    public long? InvoiceId { get; set; }
    public long? CancelApprovalId { get; set; }
    public DateTimeOffset CreatedAt { get; set; }
    public long CreatedBy { get; set; }
    /// <summary>Spec 0039 WP6 (AUD-PHI-01): the non-sequential code the public report-status
    /// lookup accepts. The order id is a walkable series printed on every receipt; this token is
    /// 16 random bytes, so an anonymous stranger can no longer enumerate orders. Printed on the
    /// test slip; generated by <see cref="Data.PublicToken.New"/>, backfilled by migration.</summary>
    public string PublicToken { get; set; } = "";
}

/// <summary>Mints <see cref="TestOrder.PublicToken"/> values: 16 random bytes as 32 hex chars.</summary>
public static class PublicToken
{
    public const int Length = 32;

    public static string New() => Convert.ToHexStringLower(
        System.Security.Cryptography.RandomNumberGenerator.GetBytes(Length / 2));

    /// <summary>What the public lookup treats as its key: trimmed, lowercased, or null when the
    /// input cannot possibly be a token — the caller answers exactly as it would for a miss.</summary>
    public static string? Normalise(string? input)
    {
        var t = input?.Trim().ToLowerInvariant();
        return t is { Length: Length } && t.All(char.IsAsciiHexDigitLower) ? t : null;
    }
}

public static class OrderTestState
{
    public const string Ordered = "ordered";
    public const string Cancelled = "cancelled";
}

public class OrderTest
{
    public long Id { get; set; }
    public long TestOrderId { get; set; }
    public long TestCatalogId { get; set; }
    public long ChargeLineId { get; set; }
    public string State { get; set; } = OrderTestState.Ordered;
    public bool Refunded { get; set; }                 // edge 21 partial refunds
}

public class DeliveryLog
{
    public long Id { get; set; }
    public long TestOrderId { get; set; }
    public int ReportVersion { get; set; }             // edge 22: which version left the building
    public DateTimeOffset DeliveredAt { get; set; }
    public string? CollectorNote { get; set; }
    public long DeliveredBy { get; set; }
}

public class DiagDbContext(DbContextOptions<DiagDbContext> options) : DbContext(options)
{

    /// <summary>The branch this context's queries are isolated to (spec 0039 WP5). Captured
    /// from the ambient request scope at construction; every entity carrying a BranchId is
    /// filtered to it structurally — see BranchIsolation.</summary>
    public long CurrentBranch { get; set; } = Hms.Kernel.Data.BranchScope.Current;
    public DbSet<TestOrder> Orders => Set<TestOrder>();
    public DbSet<OrderTest> OrderTests => Set<OrderTest>();
    public DbSet<DeliveryLog> Deliveries => Set<DeliveryLog>();

    protected override void OnModelCreating(ModelBuilder b)
    {
        // Spec 0039 WP2: the diag schema had zero indexes and zero constraints beyond the parent
        // XOR — on the tables every lab and imaging order crosses (AUD-ARCH-04, AUD-M16-10).
        b.HasDefaultSchema("diag");
        b.Entity<TestOrder>(e =>
        {
            e.ToTable("test_order", t =>
            {
                t.HasCheckConstraint(
                    "ck_test_order_parent", "num_nonnulls(encounter_id, folio_id) = 1");
                t.HasCheckConstraint("ck_test_order_state",
                    "state IN ('ordered','invoiced','in_progress','reported','delivered','cancelled')");
            });
            e.Property(x => x.State).HasMaxLength(40);
            e.Property(x => x.PublicToken).HasMaxLength(64);
            e.HasIndex(x => x.State);                            // lab board
            e.HasIndex(x => new { x.InvoiceId, x.State });       // runs on every payment
            e.HasIndex(x => x.PatientId);
            e.HasIndex(x => x.EncounterId);
            e.HasIndex(x => x.PublicToken).IsUnique();           // WP6: the public lookup key
        });
        b.Entity<OrderTest>(e =>
        {
            e.ToTable("order_test", t => t.HasCheckConstraint(
                "ck_order_test_state", "state IN ('ordered','cancelled')"));
            e.Property(x => x.State).HasMaxLength(40);
            // The join every board render does. Deliberately NOT unique on
            // (test_order_id, test_catalog_id): the same test twice on one order is a
            // legitimate clinical instruction (two views, repeat sample), each with its own
            // charge line — the schema review's unique-index suggestion was declined (ADR-0028).
            e.HasIndex(x => new { x.TestOrderId, x.TestCatalogId });
            e.HasOne<TestOrder>().WithMany().HasForeignKey(x => x.TestOrderId);
        });
        b.Entity<DeliveryLog>(e =>
        {
            e.ToTable("delivery_log");
            e.Property(x => x.CollectorNote).HasMaxLength(4000);
            e.HasIndex(x => x.TestOrderId);
            e.HasOne<TestOrder>().WithMany().HasForeignKey(x => x.TestOrderId);
        });
        // Hard rule 4: the schema must never delete on its own. Every relationship this model
        // declares refuses a parent delete instead of cascading it — corrections are reversals,
        // and a cascade is a delete machine (spec 0039 WP2, ADR-0028).
        foreach (var fk in b.Model.GetEntityTypes().SelectMany(t => t.GetForeignKeys()))
            fk.DeleteBehavior = DeleteBehavior.Restrict;
        b.ApplyBranchIsolation(this);   // WP5: branch predicate as structure (AUD-ARCH-01)
    }
}

public class DiagDbContextFactory : IDesignTimeDbContextFactory<DiagDbContext>
{
    public DiagDbContext CreateDbContext(string[] args) => new(
        new DbContextOptionsBuilder<DiagDbContext>()
            .UseNpgsql("Host=localhost;Database=hms;Username=postgres",
                o => o.MigrationsHistoryTable("__ef_migrations", "diag"))
            .UseSnakeCaseNamingConvention()
            .Options);
}
