// <auto-generated />
using System;
using Hms.Ot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hms.Ot.Data.Migrations
{
    [DbContext(typeof(OtDbContext))]
    [Migration("20260802195437_Hardening0039")]
    partial class Hardening0039
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ot")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hms.Ot.Data.CaseConsumable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("batch_no");

                    b.Property<long>("CaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("case_id");

                    b.Property<long>("ChargeLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("charge_line_id");

                    b.Property<long>("IssuedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("issued_by");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<long>("UnitPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_case_consumable");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_case_consumable_case_id");

                    b.ToTable("case_consumable", "ot", t =>
                        {
                            t.HasCheckConstraint("ck_case_consumable_qty", "qty > 0 AND unit_price >= 0");
                        });
                });

            modelBuilder.Entity("Hms.Ot.Data.CaseTeamMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AmountPosted")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_posted");

                    b.Property<long>("CaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("case_id");

                    b.Property<long?>("ChargeLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("charge_line_id");

                    b.Property<long?>("FeeServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("fee_service_id");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_id");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("person_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_case_team");

                    b.HasIndex("CaseId", "Role", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_case_team_case_id_role_person_id");

                    b.ToTable("case_team", "ot", t =>
                        {
                            t.HasCheckConstraint("ck_case_team_amount", "amount_posted >= 0");
                        });
                });

            modelBuilder.Entity("Hms.Ot.Data.OtCase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AnaesthesiaType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("anaesthesia_type");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("cancel_reason");

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("case_no");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<long?>("CompletedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("completed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<long?>("EncounterId")
                        .HasColumnType("bigint")
                        .HasColumnName("encounter_id");

                    b.Property<string>("Findings")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("findings");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<long?>("FolioId")
                        .HasColumnType("bigint")
                        .HasColumnName("folio_id");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operation_name");

                    b.Property<long>("OperationServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("operation_service_id");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<string>("ProcedurePerformed")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("procedure_performed");

                    b.Property<DateTimeOffset>("ScheduledFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_from");

                    b.Property<DateTimeOffset>("ScheduledTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_to");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("state");

                    b.Property<long>("TheatreId")
                        .HasColumnType("bigint")
                        .HasColumnName("theatre_id");

                    b.HasKey("Id")
                        .HasName("pk_ot_case");

                    b.HasIndex("CaseNo")
                        .IsUnique()
                        .HasDatabaseName("ix_ot_case_case_no");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_ot_case_patient_id");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_ot_case_state");

                    b.HasIndex("TheatreId", "ScheduledFrom")
                        .HasDatabaseName("ix_ot_case_theatre_id_scheduled_from");

                    b.ToTable("ot_case", "ot", t =>
                        {
                            t.HasCheckConstraint("ck_case_cancel_reason", "state NOT IN ('cancelled','postponed') OR cancel_reason IS NOT NULL");

                            t.HasCheckConstraint("ck_case_finished", "state <> 'completed' OR finished_at IS NOT NULL");

                            t.HasCheckConstraint("ck_case_parent", "num_nonnulls(folio_id, encounter_id) = 1");

                            t.HasCheckConstraint("ck_case_started", "state NOT IN ('in_theatre','completed') OR started_at IS NOT NULL");

                            t.HasCheckConstraint("ck_case_state", "state IN ('scheduled','patient_ready','in_theatre','completed','cancelled','postponed')");

                            t.HasCheckConstraint("ck_case_window", "scheduled_to > scheduled_from");
                        });
                });

            modelBuilder.Entity("Hms.Ot.Data.Theatre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_theatre");

                    b.HasIndex("BranchId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_theatre_branch_id_name");

                    b.ToTable("theatre", "ot");
                });

            modelBuilder.Entity("Hms.Ot.Data.CaseConsumable", b =>
                {
                    b.HasOne("Hms.Ot.Data.OtCase", null)
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_case_consumable_ot_case_case_id");
                });

            modelBuilder.Entity("Hms.Ot.Data.CaseTeamMember", b =>
                {
                    b.HasOne("Hms.Ot.Data.OtCase", null)
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_case_team_ot_case_case_id");
                });

            modelBuilder.Entity("Hms.Ot.Data.OtCase", b =>
                {
                    b.HasOne("Hms.Ot.Data.Theatre", null)
                        .WithMany()
                        .HasForeignKey("TheatreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ot_case_theatre_theatre_id");
                });
#pragma warning restore 612, 618
        }
    }
}
