// <auto-generated />
using System;
using Hms.Ot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hms.Ot.Data.Migrations
{
    [DbContext(typeof(OtDbContext))]
    partial class OtDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ot")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hms.Ot.Data.CaseConsumable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("batch_no");

                    b.Property<long>("CaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("case_id");

                    b.Property<long>("ChargeLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("charge_line_id");

                    b.Property<long>("IssuedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("issued_by");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<long>("UnitPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_case_consumable");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_case_consumable_case_id");

                    b.ToTable("case_consumable", "ot");
                });

            modelBuilder.Entity("Hms.Ot.Data.CaseTeamMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AmountPosted")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_posted");

                    b.Property<long>("CaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("case_id");

                    b.Property<long?>("ChargeLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("charge_line_id");

                    b.Property<long?>("FeeServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("fee_service_id");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_id");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("person_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_case_team");

                    b.HasIndex("CaseId", "Role", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_case_team_case_id_role_person_id");

                    b.ToTable("case_team", "ot");
                });

            modelBuilder.Entity("Hms.Ot.Data.OtCase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AnaesthesiaType")
                        .HasColumnType("text")
                        .HasColumnName("anaesthesia_type");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text")
                        .HasColumnName("cancel_reason");

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("case_no");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<long?>("CompletedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("completed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<long?>("EncounterId")
                        .HasColumnType("bigint")
                        .HasColumnName("encounter_id");

                    b.Property<string>("Findings")
                        .HasColumnType("text")
                        .HasColumnName("findings");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<long?>("FolioId")
                        .HasColumnType("bigint")
                        .HasColumnName("folio_id");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation_name");

                    b.Property<long>("OperationServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("operation_service_id");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<string>("ProcedurePerformed")
                        .HasColumnType("text")
                        .HasColumnName("procedure_performed");

                    b.Property<DateTimeOffset>("ScheduledFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_from");

                    b.Property<DateTimeOffset>("ScheduledTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_to");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<long>("TheatreId")
                        .HasColumnType("bigint")
                        .HasColumnName("theatre_id");

                    b.HasKey("Id")
                        .HasName("pk_ot_case");

                    b.HasIndex("CaseNo")
                        .IsUnique()
                        .HasDatabaseName("ix_ot_case_case_no");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_ot_case_patient_id");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_ot_case_state");

                    b.HasIndex("TheatreId", "ScheduledFrom")
                        .HasDatabaseName("ix_ot_case_theatre_id_scheduled_from");

                    b.ToTable("ot_case", "ot", t =>
                        {
                            t.HasCheckConstraint("ck_case_parent", "num_nonnulls(folio_id, encounter_id) = 1");

                            t.HasCheckConstraint("ck_case_window", "scheduled_to > scheduled_from");
                        });
                });

            modelBuilder.Entity("Hms.Ot.Data.Theatre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_theatre");

                    b.HasIndex("BranchId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_theatre_branch_id_name");

                    b.ToTable("theatre", "ot");
                });
#pragma warning restore 612, 618
        }
    }
}
